from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = load_workbook(r"C:\Users\hiro\HP0524\海外便利グッズリスト_日本未上陸405件.xlsx")
ws = wb["海外便利グッズリスト"]

cat_font = Font(name="Arial", bold=True, color="FFFFFF", size=10)
cat_fills = {
    "キッチン・調理器具": PatternFill("solid", start_color="2E75B6"),
    "スマートホーム・インテリア・照明": PatternFill("solid", start_color="538135"),
    "ウェアラブル・ヘルス・フィットネス": PatternFill("solid", start_color="7030A0"),
    "アウトドア・スポーツ・旅行": PatternFill("solid", start_color="C55A11"),
    "ペット用品": PatternFill("solid", start_color="843C0C"),
    "テクノロジー・ガジェット": PatternFill("solid", start_color="244185"),
    "美容・スキンケア": PatternFill("solid", start_color="C00000"),
    "子供・教育": PatternFill("solid", start_color="375623"),
    "ファッション・アクセサリー": PatternFill("solid", start_color="7B3F00"),
    "クリーニング・収納・整理": PatternFill("solid", start_color="404040"),
}
data_font = Font(name="Arial", size=10)
data_align = Alignment(vertical="center", wrap_text=True)
alt_fill = PatternFill("solid", start_color="EBF3FB")
thin = Side(style="thin", color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

# No.|カテゴリ|商品名|メーカー名|販売ECサイト名|商品URL|メーカーHP|連絡先メール
new_data = [
    (406,"キッチン・調理器具","Traeger Westwood WiFi Wood Pellet Grill","Traeger","Gadget Flow","https://thegadgetflow.com/product/traeger-westwood-wood-pellet-grill/","https://www.traeger.com","https://www.traeger.com/support/contact-us（問い合わせページ）"),
    (407,"キッチン・調理器具","Gozney Arc Lite 12-inch Pizza Oven","Gozney","Gadget Flow","https://thegadgetflow.com/product/gozney-arc-lite-12-inch-pizza-oven/","https://www.gozney.com","hello@gozney.com"),
    (408,"キッチン・調理器具","FoodTusker Smart Food Container","FoodTusker","Gadget Flow","https://thegadgetflow.com/product/foodtusker-smart-food-container/","https://www.foodtusker.com","https://www.foodtusker.com/contact（問い合わせページ）"),
    (409,"キッチン・調理器具","Flexi Jar V2 Modular Food Storage Jars","Flexi Jar","Gadget Flow","https://thegadgetflow.com/product/flexi-jar-v2-modular-food-storage-jars/","https://flexijar.com","https://flexijar.com/contact（問い合わせページ）"),
    (410,"スマートホーム・インテリア・照明","DeckTok Smart Foldable RGB Floor Lamp","DeckTok","Gadget Flow","https://thegadgetflow.com/product/decktok-smart-foldable-rgb-floor-lamp/","https://www.decktok.com","https://www.decktok.com/contact（問い合わせページ）"),
    (411,"スマートホーム・インテリア・照明","Nuki Keypad 2 NFC Smart Access Keypad","Nuki","Gadget Flow","https://thegadgetflow.com/product/nuki-keypad-2-nfc-smart-lock-keypad/","https://nuki.io","https://nuki.io/en/support（問い合わせページ）"),
    (412,"スマートホーム・インテリア・照明","Denon Home 600 Wireless Smart Speaker","Denon","Gadget Flow","https://thegadgetflow.com/product/denon-home-600-wireless-smart-speaker/","https://www.denon.com","https://www.denon.com/en-us/support（問い合わせページ）"),
    (413,"スマートホーム・インテリア・照明","Denon Home 400 Dolby Atmos Wireless Speaker","Denon","Gadget Flow","https://thegadgetflow.com/product/denon-home-400-wireless-smart-speaker/","https://www.denon.com","https://www.denon.com/en-us/support（問い合わせページ）"),
    (414,"スマートホーム・インテリア・照明","Fosi Audio S3 Balanced HiFi Streamer","Fosi Audio","Gadget Flow","https://thegadgetflow.com/product/fosi-audio-s3-balanced-hifi-streamer/","https://www.fosiaudio.com","support@fosiaudio.com"),
    (415,"スマートホーム・インテリア・照明","Firewalla Orange Wi-Fi 7 Firewall Router","Firewalla","Gadget Flow","https://thegadgetflow.com/product/firewalla-orange-wifi-router/","https://firewalla.com","https://help.firewalla.com（問い合わせページ）"),
    (416,"スマートホーム・インテリア・照明","Birdfy Feeder Metal 2 4K Smart Bird Feeder Camera","Birdfy","Gadget Flow","https://thegadgetflow.com/product/birdfy-feeder-metal-2-4k-smart-bird-camera/","https://www.birdfy.com","support@birdfy.com"),
    (417,"スマートホーム・インテリア・照明","Reolink Solar Floodlight Camera 2K","Reolink","Gadget Flow","https://thegadgetflow.com/product/reolink-solar-floodlight-camera/","https://reolink.com","support@reolink.com"),
    (418,"スマートホーム・インテリア・照明","Homture Magic Frame 10.1-Inch FHD WiFi Photo Frame","Homture","Gadget Flow","https://thegadgetflow.com/product/homture-magic-frame-ai-photo-to-video-digital-picture-frame/","https://www.homture.com","https://www.homture.com/contact（問い合わせページ）"),
    (419,"スマートホーム・インテリア・照明","LIFX SuperColor Mirror Smart Vanity Light","LIFX","Gadget Flow","https://thegadgetflow.com/product/lifx-supercolor-mirror-smart-bathroom-light/","https://www.lifx.com","https://www.lifx.com/pages/support（問い合わせページ）"),
    (420,"スマートホーム・インテリア・照明","Familiars Emotionally Intelligent AI Pet Robot","Familiar Machines","Gadget Flow","https://thegadgetflow.com/product/familiar-machines-magic-ai-companion-robot/","https://www.familiarmachines.com","https://www.familiarmachines.com/contact（問い合わせページ）"),
    (421,"スマートホーム・インテリア・照明","Flipper Devices BUSY Bar Productivity LED Display","Flipper Devices","Gadget Flow","https://thegadgetflow.com/product/flipper-devices-busy-bar-productivity-multi-tool-device-with-an-led-pixel-display/","https://flipperzero.one","https://flipperzero.one/contact（問い合わせページ）"),
    (422,"スマートホーム・インテリア・照明","Ubiquiti UniFi 5G Max High-Performance Modem","Ubiquiti","Gadget Flow","https://thegadgetflow.com/product/ubiquiti-unifi-5g-max-high-performance-modem/","https://www.ui.com","https://www.ui.com/support（問い合わせページ）"),
    (423,"スマートホーム・インテリア・照明","Kwikset Halifax Occupancy Indicator Door Lever","Kwikset","Gadget Flow","https://thegadgetflow.com/product/halifax-occupancy-lever-door-lock/","https://www.kwikset.com","https://www.kwikset.com/support/contact-us（問い合わせページ）"),
    (424,"ウェアラブル・ヘルス・フィットネス","QALO QRNT Titanium Smart Ring No Subscription","QALO","Gadget Flow","https://thegadgetflow.com/product/qalo-qrnt-smart-ring/","https://www.qalo.com","support@qalo.com"),
    (425,"ウェアラブル・ヘルス・フィットネス","Myzone Switch 2.0 Heart Rate Monitor","Myzone","Gadget Flow","https://thegadgetflow.com/product/myzone-switch-2-0-heart-rate-monitor/","https://www.myzone.org","support@myzone.org"),
    (426,"ウェアラブル・ヘルス・フィットネス","FORM Smart Swim 2 LT Real-Time Swim Goggles","FORM","Gadget Flow","https://thegadgetflow.com/product/smart-swim-2-lt-goggles/","https://www.formswim.com","support@formswim.com"),
    (427,"ウェアラブル・ヘルス・フィットネス","Natural Cycles NC° Band Fertility Wearable","Natural Cycles","Gadget Flow","https://thegadgetflow.com/product/natural-cycles-nc-band-fertility-wearable/","https://www.naturalcycles.com","https://www.naturalcycles.com/en/contact（問い合わせページ）"),
    (428,"ウェアラブル・ヘルス・フィットネス","Altair Smart Posture Pad for Chair Posture Tracking","Resit","Gadget Flow","https://thegadgetflow.com/product/resit-altair-smart-posture-pad/","https://www.resit.com","https://www.resit.com/contact（問い合わせページ）"),
    (429,"ウェアラブル・ヘルス・フィットネス","SuperMouth ULTIM8 SmartBrush System","SuperMouth","Gadget Flow","https://thegadgetflow.com/product/supermouth-ultim8-smartbrush-system/","https://supermouth.com","hello@supermouth.com"),
    (430,"ウェアラブル・ヘルス・フィットネス","FLAUS Electric Flosser Kit 3 Speeds 45 Heads","FLAUS","Gadget Flow","https://thegadgetflow.com/product/flaus-electric-flosser/","https://www.flaus.com","hello@flaus.com"),
    (431,"ウェアラブル・ヘルス・フィットネス","Elitone Pelvic Floor Exerciser","Elitone","Gadget Flow","https://thegadgetflow.com/product/elitone-non-invasive-pelvic-floor-exerciser/","https://www.elitone.com","support@elitone.com"),
    (432,"ウェアラブル・ヘルス・フィットネス","OhmBody Starter Kit Menstrual Relief Device","OhmBody","Gadget Flow","https://thegadgetflow.com/product/ohmbody-starter-kit-menstrual-relief/","https://www.ohmbody.com","hello@ohmbody.com"),
    (433,"ウェアラブル・ヘルス・フィットネス","Eli Health Hormometer Saliva-Based Hormone Testing Kit","Eli Health","Gadget Flow","https://thegadgetflow.com/product/eli-health-hormometer-saliva-based-at-home-hormone-testing-kit/","https://www.eli.health","https://www.eli.health/contact（問い合わせページ）"),
    (434,"ウェアラブル・ヘルス・フィットネス","Mira Ultra4 Hormone Tracking Wands","Mira","Gadget Flow","https://thegadgetflow.com/product/mira-ultra4-wands-hormone-test/","https://www.miracare.com","support@miracare.com"),
    (435,"ウェアラブル・ヘルス・フィットネス","Orka O1 Pro Hearing Aid with Bose QuietControl ANC","Orka","Gadget Flow","https://thegadgetflow.com/product/orka-o1-pro-hearing-aid-with-bose-quietcontrol-anc-technology/","https://www.hiorka.com","support@hiorka.com"),
    (436,"ウェアラブル・ヘルス・フィットネス","4iiii Viiiiva ANT+ Bluetooth Heart Rate Monitor","4iiii","Gadget Flow","https://thegadgetflow.com/product/viiiiva-heart-rate-monitor/","https://www.4iiii.com","https://4iiii.com/pages/contact（問い合わせページ）"),
    (437,"ウェアラブル・ヘルス・フィットネス","Livlab HoomBand Ultimate Wireless Sleep Headphones","Livlab","Gadget Flow","https://thegadgetflow.com/product/livlab-hoomband-ultimate-wireless-sleep-headphones/","https://www.livlab.com","contact@livlab.com"),
    (438,"ウェアラブル・ヘルス・フィットネス","Hypershell X Ultra AI-Powered Outdoor Exoskeleton","Hypershell","Gadget Flow","https://thegadgetflow.com/product/hypershell-x-ultra-ai-powered-outdoor-exoskeleton/","https://www.hypershell.tech","https://www.hypershell.tech/contact（問い合わせページ）"),
    (439,"アウトドア・スポーツ・旅行","Optimus Gemini II Propane Camping Stove","Optimus","Gadget Flow","https://thegadgetflow.com/product/katadyn-optimus-gemini-ii-camping-stove/","https://www.optimusstoves.com","https://www.optimusstoves.com/contact（問い合わせページ）"),
    (440,"アウトドア・スポーツ・旅行","Vespera II Smart Telescope","Vespera (Vaonis)","Gadget Flow","https://thegadgetflow.com/product/vespera-ii-smart-telescope/","https://vaonis.com","contact@vaonis.com"),
    (441,"アウトドア・スポーツ・旅行","Beeline Moto II Motorcycle GPS Tracker","Beeline","Gadget Flow","https://thegadgetflow.com/product/beeline-moto-ii-next-gen-motorcycle-gps-tracker/","https://www.beeline.co","https://www.beeline.co/contact（問い合わせページ）"),
    (442,"アウトドア・スポーツ・旅行","Vallon Crossroads All-Mountain Ski Goggles","Vallon","Gadget Flow","https://thegadgetflow.com/product/vallon-crossroads-all-mountain-ski-goggles/","https://vallon-sunglasses.com","hello@vallon-sunglasses.com"),
    (443,"アウトドア・スポーツ・旅行","Matata Xplore Solvia ED 8x32 AI Binoculars","Matata","Gadget Flow","https://thegadgetflow.com/product/matata-xplore-solvia-ed-8x32-ai-binoculars/","https://www.matataxplore.com","https://www.matataxplore.com/contact（問い合わせページ）"),
    (444,"アウトドア・スポーツ・旅行","POCKITROD Modular Multi-Tool EDC System","POCKITROD","Gadget Flow","https://thegadgetflow.com/product/pockitrod-modular-multi-tool-edc-multitool/","https://www.pockitrod.com","https://www.pockitrod.com/contact（問い合わせページ）"),
    (445,"アウトドア・スポーツ・旅行","Soundboks Mix Bluetooth Party Speaker","Soundboks","Gadget Flow","https://thegadgetflow.com/product/soundboks-mix-bluetooth-party-speaker/","https://www.soundboks.com","support@soundboks.com"),
    (446,"アウトドア・スポーツ・旅行","OUTZAC PICO PUMP Portable Air Pump","OUTZAC","Gadget Flow","https://thegadgetflow.com/product/outzac-pico-pump-portable-air-pump/","https://www.outzac.com","https://www.outzac.com/contact（問い合わせページ）"),
    (447,"アウトドア・スポーツ・旅行","CIGMAN CNVPRO Full-Color Night Vision Goggles","CIGMAN","Gadget Flow","https://thegadgetflow.com/product/cnvpro-full-color-night-vision-goggles/","https://www.cigman.com","support@cigman.com"),
    (448,"アウトドア・スポーツ・旅行","TALIX Zeta Modular Power Station","TALIX","Gadget Flow","https://thegadgetflow.com/product/talix-zeta-modular-power-station/","https://www.talix.com","https://www.talix.com/contact（問い合わせページ）"),
    (449,"アウトドア・スポーツ・旅行","LOPKIN E-SERIES Smart Robot Lawn Mower","LOPKIN","Gadget Flow","https://thegadgetflow.com/product/lopkin-e-series-robot-mower/","https://www.lopkin.com","https://www.lopkin.com/contact（問い合わせページ）"),
    (450,"アウトドア・スポーツ・旅行","Preppi Solar Laptop & Phone Charger","Preppi","Gadget Flow","https://thegadgetflow.com/product/preppi-solar-laptop-phone-charger-portable-solar-panel/","https://www.preppi.com","https://www.preppi.com/contact（問い合わせページ）"),
    (451,"アウトドア・スポーツ・旅行","BLAVOR PN-W43 Portable Power Station","BLAVOR","Gadget Flow","https://thegadgetflow.com/product/blavor-pn-w43-portable-power-station/","https://www.blavor.com","support@blavor.com"),
    (452,"アウトドア・スポーツ・旅行","GSI Outdoors Glacier Insulated 4-Piece Travel Stack Set","GSI Outdoors","Gadget Flow","https://thegadgetflow.com/product/gsi-glacier-insulated-travel-stack/","https://www.gsioutdoors.com","customerservice@gsioutdoors.com"),
    (453,"アウトドア・スポーツ・旅行","DECKED Tool Box Waterproof Truck Bed","DECKED","Gadget Flow","https://thegadgetflow.com/product/decked-tool-box-waterproof-truck-bed-tool-box/","https://www.decked.com","support@decked.com"),
    (454,"アウトドア・スポーツ・旅行","Ninja Fireside360 Outdoor Heater & Fire Pit","Shark Ninja","Gadget Flow","https://thegadgetflow.com/product/ninja-fireside360-outdoor-heater-fire-pit/","https://www.ninjakitchen.com","https://www.ninjakitchen.com/support/contact（問い合わせページ）"),
    (455,"アウトドア・スポーツ・旅行","Bandletic Atlas Outdoor Case Band for Apple Watch","Bandletic","Gadget Flow","https://thegadgetflow.com/product/bandletic-atlas-outdoor-case-band-for-your-apple-watch/","https://www.bandletic.com","hello@bandletic.com"),
    (456,"アウトドア・スポーツ・旅行","Traeger Irontop Series Outdoor Griddle","Traeger","Gadget Flow","https://thegadgetflow.com/product/traeger-irontop-series-outdoor-griddles/","https://www.traeger.com","https://www.traeger.com/support/contact-us（問い合わせページ）"),
    (457,"アウトドア・スポーツ・旅行","Nikon PROSTAFF P7 Binoculars","Nikon","Gadget Flow","https://thegadgetflow.com/product/nikon-prostaff-p7-binoculars/","https://www.nikonusa.com","https://www.nikonusa.com/en/service-and-support/contact-us.page（問い合わせページ）"),
    (458,"ペット用品","Halo Collar 5 GPS Dog Fence","Halo","Gadget Flow","https://thegadgetflow.com/product/halo-collar-5-gps-dog-fence/","https://www.halocollar.com","support@halocollar.com"),
    (459,"ペット用品","SATELLAI Collar Go Smart GPS Dog Collar","SATELLAI","Gadget Flow","https://thegadgetflow.com/product/satellai-collar-go-smart-gps-dog-collar/","https://www.satellai.com","https://www.satellai.com/contact（問い合わせページ）"),
    (460,"ペット用品","Cheerble Pet Feeder Match G1 AI Pet Feeder","Cheerble","Gadget Flow","https://thegadgetflow.com/product/pet-feeder-match-g1-ai-pet-feeder/","https://www.cheerble.com","support@cheerble.com"),
    (461,"ペット用品","Tuanty Pet Fresh Food Maker","Tuanty","Gadget Flow","https://thegadgetflow.com/product/tuanty-pet-fresh-food-maker/","https://www.tuanty.com","https://www.tuanty.com/contact（問い合わせページ）"),
    (462,"ペット用品","GlocalMe PetPhone C-Plus Suite","GlocalMe","Gadget Flow","https://thegadgetflow.com/product/glocalme-petphone-c-plus-suite/","https://www.glocalme.com","support@glocalme.com"),
    (463,"ペット用品","homerunPET Pet-Friendly Space Heater PH20","homerunPET","Gadget Flow","https://thegadgetflow.com/product/pet-friendly-space-heater-ph20-heater/","https://www.homerunpet.com","https://www.homerunpet.com/contact（問い合わせページ）"),
    (464,"ペット用品","Siipet PawTrack Camera","Siipet","Gadget Flow","https://thegadgetflow.com/product/siipet-pawtrack-camera/","https://www.siipet.com","https://www.siipet.com/contact（問い合わせページ）"),
    (465,"ペット用品","Pawly Smart Self-Cleaning Dog Bowl Washer","Pawly","Gadget Flow","https://thegadgetflow.com/product/pawly-smart-self-cleaning-dog-bowl-washer/","https://www.pawly.com","https://www.pawly.com/contact（問い合わせページ）"),
    (466,"ペット用品","Dreame Pet Purifier AP10","Dreame Technology","Gadget Flow","https://thegadgetflow.com/product/dreame-pet-purifier-ap10-pet-air-purifier/","https://www.dreametech.com","support@dreametech.com"),
    (467,"ペット用品","LG PuriCare AeroCat Tower Air Purifier","LG","Gadget Flow","https://thegadgetflow.com/product/lg-puricare-aerocat-tower-air-purifier/","https://www.lg.com","https://www.lg.com/us/support/contact-us（問い合わせページ）"),
    (468,"ペット用品","Enabot EBO Max FamilyBot AI Home Camera Robot","Enabot","Gadget Flow","https://thegadgetflow.com/product/enabot-ebo-max-familybot-ai-powered-home-camera-robot/","https://www.enabot.com","support@enabot.com"),
    (469,"ペット用品","PETPA Multi-Pet Feeder","PETPA","Gadget Flow","https://thegadgetflow.com/product/petpa-multi-pet-feeder/","https://www.petpa.com","https://www.petpa.com/contact（問い合わせページ）"),
    (470,"ペット用品","Uproot 7-in-1 Clean Pet Grooming Vacuum Kit","Uproot","Gadget Flow","https://thegadgetflow.com/product/uproot-7in1-clean-pet-grooming-vacuum-kit/","https://www.uprootclean.com","hello@uprootclean.com"),
    (471,"ペット用品","Modkat Flip Litter Box","Modkat","Gadget Flow","https://thegadgetflow.com/product/modkat-flip-litter-box/","https://www.modkat.com","https://www.modkat.com/pages/contact（問い合わせページ）"),
    (472,"ペット用品","Purina Petivity Smart Litter Box Monitor","Purina","Gadget Flow","https://thegadgetflow.com/product/purina-petivity-smart-litter-box-monitor/","https://www.petivity.com","https://www.petivity.com/contact（問い合わせページ）"),
    (473,"テクノロジー・ガジェット","XREAL One Pro XR Glasses","XREAL","Gadget Flow","https://thegadgetflow.com/product/xreal-one-pro/","https://www.xreal.com","support@xreal.com"),
    (474,"テクノロジー・ガジェット","VITURE Luma Pro XR Glasses","VITURE","Gadget Flow","https://thegadgetflow.com/product/viture-luma-pro-xr-glasses-with-customizable-rgb-lighting/","https://www.viture.com","support@viture.com"),
    (475,"テクノロジー・ガジェット","Brilliant Labs Halo AI Glasses","Brilliant Labs","Gadget Flow","https://thegadgetflow.com/product/halo-ai-glasses/","https://brilliant.xyz","hello@brilliant.xyz"),
    (476,"テクノロジー・ガジェット","RayNeo Air 4 Pro AR Glasses","RayNeo","Gadget Flow","https://thegadgetflow.com/product/rayneo-air-4-pro-and-batman-edition-ar-glasses/","https://www.rayneo.com","support@rayneo.com"),
    (477,"テクノロジー・ガジェット","Bebird EarSight Ultra X 5G Ear Care Device","Bebird","Gadget Flow","https://thegadgetflow.com/product/bebird-earsight-ultra-x-5g-powered-ear-care-device/","https://www.bebird.com","support@bebird.com"),
    (478,"テクノロジー・ガジェット","CRKD ATOM+ Mini Bluetooth Gaming Controller","CRKD","Gadget Flow","https://thegadgetflow.com/product/crkd-atomplus-mini-bluetooth-gaming-controller/","https://crkd.com","https://crkd.com/pages/contact（問い合わせページ）"),
    (479,"テクノロジー・ガジェット","HIFI WALKER H2 Mini Hi-Res Music Player","HIFI WALKER","Gadget Flow","https://thegadgetflow.com/product/hifi-walker-h2-mini-hi-res-music-player/","https://www.hifiwalker.com","support@hifiwalker.com"),
    (480,"テクノロジー・ガジェット","Meze Audio ASTRU In-Ear Monitor","Meze Audio","Gadget Flow","https://thegadgetflow.com/product/meze-audio-astru-in-ear-headphones/","https://mezeaudio.com","contact@mezeaudio.com"),
    (481,"テクノロジー・ガジェット","DALI VEGA Wireless All-in-One Speaker System","DALI","Gadget Flow","https://thegadgetflow.com/product/dali-vega-wireless-all-in-one-speaker-system/","https://www.dali-speakers.com","https://www.dali-speakers.com/en/contact（問い合わせページ）"),
    (482,"テクノロジー・ガジェット","Marshall Milton A.N.C. Wireless Headphones","Marshall","Gadget Flow","https://thegadgetflow.com/product/marshall-milton-a-n-c-wireless-headphones-with-adaptive-active-noise-cancellation/","https://www.marshallheadphones.com","https://www.marshallheadphones.com/pages/contact（問い合わせページ）"),
    (483,"テクノロジー・ガジェット","Marshall Bromley 450 Portable Party Speaker","Marshall","Gadget Flow","https://thegadgetflow.com/product/marshall-bromley-450-portable-party-speaker/","https://www.marshallheadphones.com","https://www.marshallheadphones.com/pages/contact（問い合わせページ）"),
    (484,"テクノロジー・ガジェット","Skullcandy Push 540 Open True Wireless Earbuds","Skullcandy","Gadget Flow","https://thegadgetflow.com/product/skullcandy-push-540-open-true-wireless-earbuds/","https://www.skullcandy.com","https://www.skullcandy.com/contact（問い合わせページ）"),
    (485,"テクノロジー・ガジェット","Teenage Engineering field OB-4 Speaker Case","Teenage Engineering","Gadget Flow","https://thegadgetflow.com/product/teenage-engineering-field-ob-4-shoulder-bag-speaker-case/","https://teenage.engineering","https://teenage.engineering/support（問い合わせページ）"),
    (486,"テクノロジー・ガジェット","Lexar TouchLock Portable SSD External Drive","Lexar","Gadget Flow","https://thegadgetflow.com/product/lexar-touchlock-portable-ssd-external-drive/","https://www.lexar.com","https://www.lexar.com/en_US/support/contact-us.html（問い合わせページ）"),
    (487,"テクノロジー・ガジェット","INIU Cougar P63 Laptop Power Bank 25000mAh","INIU","Gadget Flow","https://thegadgetflow.com/product/iniu-cougar-p63-laptop-power-bank-with-25000-mah-battery/","https://www.iniuniversal.com","support@iniuniversal.com"),
    (488,"テクノロジー・ガジェット","TESSAN Voyager 205 Universal Travel Adapter","TESSAN","Gadget Flow","https://thegadgetflow.com/product/tessan-205w-travel-charger/","https://www.tessan.com","support@tessan.com"),
    (489,"テクノロジー・ガジェット","AULUMU M10 Multi-Charging Dual-Mag Power Bank","AULUMU","Gadget Flow","https://thegadgetflow.com/product/aulumu-m10-multi-charging-dual-mag-power-bank/","https://www.aulumu.com","https://www.aulumu.com/contact（問い合わせページ）"),
    (490,"テクノロジー・ガジェット","STATIK MagStack Pro 100W USB-C Magnetic Cable","STATIK","Gadget Flow","https://thegadgetflow.com/product/statik-magstack-pro-100-w-usb-c-to-usb-c-magnetic-cable/","https://www.statik.co","https://www.statik.co/contact（問い合わせページ）"),
    (491,"テクノロジー・ガジェット","Forming Function Nomad Strip 03 Power Outlet","Forming Function","Gadget Flow","https://thegadgetflow.com/product/nomad-strip-03-power-outlet/","https://www.formingfunction.com","https://www.formingfunction.com/contact（問い合わせページ）"),
    (492,"テクノロジー・ガジェット","ALPAKA x Twelve South Micro Tote Organizer","ALPAKA","Gadget Flow","https://thegadgetflow.com/product/alpaka-twelve-south-micro-tote-organizer/","https://www.alpakagear.com","https://www.alpakagear.com/pages/contact-us（問い合わせページ）"),
    (493,"テクノロジー・ガジェット","NeoMag EDC Tray TAD Edition Gear Organizer","NeoMag","Gadget Flow","https://thegadgetflow.com/product/neomag-edc-tray-tad-edition-gear-organizer/","https://www.neomag.com","https://www.neomag.com/contact（問い合わせページ）"),
    (494,"テクノロジー・ガジェット","Titaner Quick-Release EDC Carry System","Titaner","Gadget Flow","https://thegadgetflow.com/product/titaner-quick-release-edc-carry-system/","https://www.titaner.com","https://www.titaner.com/contact（問い合わせページ）"),
    (495,"テクノロジー・ガジェット","lemmo zero Folding Electric Bike","lemmo","Gadget Flow","https://thegadgetflow.com/product/lemmo-zero-folding-electric-bike/","https://www.lemmo.bike","https://www.lemmo.bike/contact（問い合わせページ）"),
    (496,"テクノロジー・ガジェット","MOVA MOBIUS 60 Robot Vacuum and Mop","MOVA","Gadget Flow","https://thegadgetflow.com/product/mova-mobius-60-robot-vacuum-and-mop/","https://www.mova-robot.com","support@mova-robot.com"),
    (497,"テクノロジー・ガジェット","DJI ROMO A Robot Vacuum and Mop","DJI","DJI公式サイト","https://thegadgetflow.com/product/dji-romo-a-robot-vacuum-and-mop/","https://www.dji.com/romo","https://www.dji.com/support/other（問い合わせページ）"),
    (498,"テクノロジー・ガジェット","Fort Strength-Tracking Wearable","Fort","Gadget Flow","https://thegadgetflow.com/product/fort-strength-tracking-wearable/","https://www.fortfit.com","https://www.fortfit.com/contact（問い合わせページ）"),
    (499,"テクノロジー・ガジェット","Hengbot Sirius Agile Robotic Dog","Hengbot","Gadget Flow","https://thegadgetflow.com/product/hengbot-sirius/","https://www.hengbot.com","contact@hengbot.com"),
    (500,"テクノロジー・ガジェット","Xtra Atto 54g 4K Creator Camera","Xtra","Gadget Flow","https://thegadgetflow.com/product/xtra-atto-54g-4k-creator-camera/","https://www.xtra.camera","https://www.xtra.camera/contact（問い合わせページ）"),
    (501,"テクノロジー・ガジェット","ASCAND Portable Precision 3D Color Laser Scanner","ASCAND","Gadget Flow","https://thegadgetflow.com/product/ascand-3d-laser-scanner-turns-your-phone-into-pro-portable-affordable-scanner/","https://www.ascand.com","https://www.ascand.com/contact（問い合わせページ）"),
    (502,"テクノロジー・ガジェット","Orbitkey Nest v2 Customizable Desk Organizer","Orbitkey","Gadget Flow","https://thegadgetflow.com/product/orbitkey-nest-v2-customizable-desk-organizer/","https://www.orbitkey.com","https://www.orbitkey.com/pages/contact（問い合わせページ）"),
    (503,"美容・スキンケア","Omnilux Mini Blemish Eraser Blue and Red Light Therapy","Omnilux","Gadget Flow","https://thegadgetflow.com/product/omnilux-mini-blemish-eraser-blue-and-red-light-therapy-device/","https://www.omniluxled.com","info@omniluxled.com"),
    (504,"美容・スキンケア","JOVS 4D Laser Light Therapy Mask","JOVS","Gadget Flow","https://thegadgetflow.com/product/jovs-4d-laser-light-therapy-mask-beauty-device/","https://www.jovs.com","support@jovs.com"),
    (505,"美容・スキンケア","Laifen SE 2 High-Speed Hair Dryer","Laifen","Gadget Flow","https://thegadgetflow.com/product/laifen-se-2-high-speed-hair-dryer/","https://www.laifen.com","support@laifen.com"),
    (506,"美容・スキンケア","Laifen Mini High-Speed Portable Hair Dryer","Laifen","Gadget Flow","https://thegadgetflow.com/product/laifen-mini-high-speed-hair-dryer-travel-dryer/","https://www.laifen.com","support@laifen.com"),
    (507,"美容・スキンケア","Laifen Wave Pro Electric Toothbrush","Laifen","Gadget Flow","https://thegadgetflow.com/product/laifen-wave-pro-electric-toothbrush/","https://www.laifen.com","support@laifen.com"),
    (508,"美容・スキンケア","Laifen T1 Pro Electric Shaver","Laifen","Gadget Flow","https://thegadgetflow.com/product/laifen-t1-pro-electric-shaver/","https://www.laifen.com","support@laifen.com"),
    (509,"美容・スキンケア","Frosteam All-in-One Facial Spa","Frosteam","Gadget Flow","https://thegadgetflow.com/product/frosteam-all-in-one-facial-spa/","https://www.frosteam.com","https://www.frosteam.com/contact（問い合わせページ）"),
    (510,"美容・スキンケア","Rootique DUO Micro Misting Hair Tonic Applicator","Rootique","Gadget Flow","https://thegadgetflow.com/product/rootique-duo-micro-misting-hair-tonic-applicator/","https://www.rootique.com","hello@rootique.com"),
    (511,"美容・スキンケア","FOREO FLIP Play Advanced LED Hairbrush","FOREO","Gadget Flow","https://thegadgetflow.com/product/flip-play-advanced-led-light-hairbrush/","https://www.foreo.com","https://www.foreo.com/pages/contact（問い合わせページ）"),
    (512,"美容・スキンケア","L'Oréal LED Face Mask","L'Oréal","Gadget Flow","https://thegadgetflow.com/product/loreal-led-face-mask-beauty-device/","https://www.loreal.com","https://www.lorealparisusa.com/contact-us（問い合わせページ）"),
    (513,"美容・スキンケア","L'Oréal Light Straight+ Multi-Styler","L'Oréal","Gadget Flow","https://thegadgetflow.com/product/loreal-light-straight-multi-styler-hair-straightener/","https://www.loreal.com","https://www.lorealparisusa.com/contact-us（問い合わせページ）"),
    (514,"美容・スキンケア","Dreame Pilot 20 AI Intelligent Luxury Hair Dryer","Dreame Technology","Gadget Flow","https://thegadgetflow.com/product/dreame-pilot-20-ai-intelligent-luxury-hair-dryer/","https://www.dreametech.com","support@dreametech.com"),
    (515,"美容・スキンケア","Dreame AirStyle Pro Hair Styler","Dreame Technology","Gadget Flow","https://thegadgetflow.com/product/dreame-airstyle-pro/","https://www.dreametech.com","support@dreametech.com"),
    (516,"美容・スキンケア","blendSMART Rotating Makeup Brush Set","blendSMART","Gadget Flow","https://thegadgetflow.com/product/blendsmart-rotating-makeup-brush-set/","https://www.blendsmart.com","hello@blendsmart.com"),
    (517,"美容・スキンケア","FADETTE Aircell Roller Puff Multifunctional Beauty Tool","FADETTE","Gadget Flow","https://thegadgetflow.com/product/fadette-aircell-roller-puff-multifunctional-beauty-tools/","https://www.fadette.com","https://www.fadette.com/contact（問い合わせページ）"),
    (518,"美容・スキンケア","COSLUS C30 Water Dental Flosser","COSLUS","Gadget Flow","https://thegadgetflow.com/product/coslus-c30-water-dental-flosser-pick-for-teeth/","https://www.coslus.com","support@coslus.com"),
    (519,"美容・スキンケア","MYTREX EMS Head Spa Pro Scalp Massager","MYTREX","Gadget Flow","https://thegadgetflow.com/product/mytrex-ems-head-spa-scalp-massager/","https://www.mytrex.jp","https://www.mytrex.jp/contact（問い合わせページ）"),
    (520,"美容・スキンケア","Ulike ReGlow Ergonomic LED Face Mask","Ulike","Gadget Flow","https://thegadgetflow.com/product/ulike-reglow-ergonomic-led-face-mask/","https://www.ulike.com","support@ulike.com"),
    (521,"美容・スキンケア","Meridian The Trimmer Premium Personal Hair Trimmer","Meridian","Gadget Flow","https://thegadgetflow.com/product/meridian-the-trimmer-premium-personal-hair-trimmer/","https://www.meridiangrooming.com","https://www.meridiangrooming.com/pages/contact（問い合わせページ）"),
    (522,"美容・スキンケア","Hedgehog GO Dual-Purpose Portable Hair Dryer","Hedgehog","Gadget Flow","https://thegadgetflow.com/product/hedgehog-go-dual-purpose-portable-dryer/","https://www.hedgehoggo.com","https://www.hedgehoggo.com/contact（問い合わせページ）"),
    (523,"美容・スキンケア","Shark CryoGlow LED Face Mask","Shark Beauty","Amazon.com","https://thegadgetflow.com/product/shark-cryoglow-led-face-mask/","https://www.sharkbeauty.com","https://www.sharkbeauty.com/pages/contact（問い合わせページ）"),
    (524,"美容・スキンケア","Sony REON POCKET PRO Plus Personal Wearable Cooler","Sony","Sony公式サイト","https://thegadgetflow.com/product/reon-pocket-pro-plus-wearable-cooler/","https://www.sony.com","https://www.sony.com/en_US/support（問い合わせページ）"),
    (525,"美容・スキンケア","NOVA H1 Audio Earrings Wireless Earphones in Earrings","Icebach Sound Solutions","Gadget Flow","https://thegadgetflow.com/product/nova-h1-audio-earrings-are-pair-of-wireless-earphones-embedded-in-pair-of-earrings/","https://icebachsound.com","hello@icebachsound.com"),
    (526,"美容・スキンケア","Nirva AI-Powered Wearable Necklace Bracelet","Nirva Labs","Gadget Flow","https://thegadgetflow.com/product/nirva-necklace-bracelet-ai-powered-wearable/","https://www.nirvalabs.com","https://www.nirvalabs.com/contact（問い合わせページ）"),
    (527,"子供・教育","CODEE Screen-Free AI Coding Robot Lab for Kids","CODEE","Gadget Flow","https://thegadgetflow.com/product/codee-ai-powered-coding-lab/","https://www.codee.ai","hello@codee.ai"),
    (528,"子供・教育","Luka AI Cube Child-Safe Outdoor Learning Companion","Luka","Gadget Flow","https://thegadgetflow.com/product/luka-ai-cube-kids-learning-robot/","https://www.luka.ai","https://www.luka.ai/contact（問い合わせページ）"),
    (529,"子供・教育","Tin Can Kids WiFi Phone for Voice-Only Calling","Tin Can Kids","Gadget Flow","https://thegadgetflow.com/product/tin-can-phone-for-kids/","https://www.tincankids.com","hello@tincankids.com"),
    (530,"子供・教育","Gabb Watch 3e Smartwatch with GPS & SOS for Kids","Gabb","Gadget Flow","https://thegadgetflow.com/product/gabb-watch-3e-smart-watch/","https://www.gabb.com","support@gabb.com"),
    (531,"子供・教育","Stickerbox AI Sticker Printer Kid-Safe","Stickerbox","Gadget Flow","https://thegadgetflow.com/product/stickerbox-ai-sticker-printer/","https://www.stickerboxprinter.com","https://www.stickerboxprinter.com/contact（問い合わせページ）"),
    (532,"子供・教育","Yonbo X1 AI Companion Robot for Kids & Families","Yonbo","Gadget Flow","https://thegadgetflow.com/product/yonbo-x1-advanced-ai-companion-robot/","https://www.yonborobot.com","https://www.yonborobot.com/contact（問い合わせページ）"),
    (533,"子供・教育","OlloBot Cyber Pet Robot Companion for Home","OlloBot","Gadget Flow","https://thegadgetflow.com/product/ollobot-cyber-pet-robot/","https://www.ollobot.com","https://www.ollobot.com/contact（問い合わせページ）"),
    (534,"子供・教育","Sweekar AI Pet Companion with Physical Growth","Sweekar","Gadget Flow","https://thegadgetflow.com/product/sweekar-ai-pet-physically-growing-companion/","https://www.sweekar.com","https://www.sweekar.com/contact（問い合わせページ）"),
    (535,"子供・教育","Teeni.AI Mooni Pro Portable AI Robot for Kids","Teeni.AI","Gadget Flow","https://thegadgetflow.com/product/teeni-ai-mooni-pro/","https://www.teeni.ai","hello@teeni.ai"),
    (536,"子供・教育","Willo BrushBot Kids Toothbrush Starter Kit","Willo","Gadget Flow","https://thegadgetflow.com/product/willo-brushbot-kids-toothbrush-starter-kit-kids-electric-toothbrush/","https://www.hellowillo.com","hello@hellowillo.com"),
    (537,"子供・教育","myFirst Frame Clario 7\" Wi-Fi Digital Picture Frame","myFirst","Gadget Flow","https://thegadgetflow.com/product/myfirst-frame-clario-digital-picture-frame/","https://www.myfirst.store","https://www.myfirst.store/contact（問い合わせページ）"),
    (538,"子供・教育","CrunchLabs HackPack STEM Subscription Boxes","CrunchLabs","Gadget Flow","https://thegadgetflow.com/product/crunchlabs-hackpack-stem-subscription-boxes/","https://www.crunchlabs.com","https://www.crunchlabs.com/contact（問い合わせページ）"),
    (539,"子供・教育","SparkBlocks STEM Blocks Compatible with LEGO","SparkBlocks","Gadget Flow","https://thegadgetflow.com/product/sparkblocks-stem-blocks-for-lego-bricks/","https://www.sparkblocks.com","https://www.sparkblocks.com/contact（問い合わせページ）"),
    (540,"子供・教育","ilo Educational Robot Kit","ilo","Gadget Flow","https://thegadgetflow.com/product/ilo-robot-educational-robot/","https://www.ilorobot.com","hello@ilorobot.com"),
    (541,"子供・教育","Pollen Robotics Reachy Mini Desktop Robot","Pollen Robotics","Gadget Flow","https://thegadgetflow.com/product/pollen-robotics-reachy-mini-desktop-robot/","https://www.pollen-robotics.com","contact@pollen-robotics.com"),
    (542,"子供・教育","CircuitMess Space Rover AI Kit","CircuitMess","Gadget Flow","https://thegadgetflow.com/product/geek-club-circuitmess-space-rover-ai-powered-kit/","https://www.circuitmess.com","hello@circuitmess.com"),
    (543,"子供・教育","Chompshop ChompSaw Kid-Safe Cardboard Cutter","Chompshop","Gadget Flow","https://thegadgetflow.com/product/chompshop-chompsaw-kid-safe-cardboard-cutter/","https://www.chompshop.com","https://www.chompshop.com/contact（問い合わせページ）"),
    (544,"子供・教育","ThinkFun Gravity Maze Builder Board Game","ThinkFun","Gadget Flow","https://thegadgetflow.com/product/thinkfun-gravity-maze-builder-board-game/","https://www.thinkfun.com","https://www.thinkfun.com/support（問い合わせページ）"),
    (545,"子供・教育","Darwin MX Pro Smart Digital Microscope","Darwin","Gadget Flow","https://thegadgetflow.com/product/darwin-mx-pro-smart-digital-microscope/","https://www.darwinmicro.com","https://www.darwinmicro.com/contact（問い合わせページ）"),
    (546,"子供・教育","UBTECH UGOT Robotic Kit","UBTECH","Gadget Flow","https://thegadgetflow.com/product/ubtech-ugot-robotic-kit/","https://www.ubtrobot.com","https://www.ubtrobot.com/pages/contact（問い合わせページ）"),
    (547,"子供・教育","Petoi Bittle STEM Kit Robot Dog","Petoi","Gadget Flow","https://thegadgetflow.com/product/petoi-bittle-stem-kit-little-opensource-robot-dog-does-trick-for-both-fun-learning/","https://www.petoi.com","hello@petoi.com"),
    (548,"子供・教育","FEEL FLUX Scientific Desk Toy Collection","FEEL FLUX","Gadget Flow","https://thegadgetflow.com/product/feel-flux-scientific-desk-toy-collection/","https://www.feelflux.com","hello@feelflux.com"),
    (549,"子供・教育","Board Face-to-Face 24-inch Interactive Game Console","Board","Gadget Flow","https://thegadgetflow.com/product/board-signature-edition-game-console/","https://www.playboard.com","https://www.playboard.com/contact（問い合わせページ）"),
    (550,"子供・教育","TCL MOVETIME MT48 Kids Smartwatch 4G GPS","TCL","TCL公式サイト","https://thegadgetflow.com/product/tcl-movetime-mt48-kids-smartwatch/","https://www.tcl.com","https://www.tcl.com/us/en/support/contact（問い合わせページ）"),
    (551,"子供・教育","TCL Tbot AI Desktop Companion with Magnetic Base","TCL","TCL公式サイト","https://thegadgetflow.com/product/tcl-tbot-ai-desktop-companion/","https://www.tcl.com","https://www.tcl.com/us/en/support/contact（問い合わせページ）"),
    (552,"子供・教育","BAOBAO Dual-Mode Home Robot for Family Fun","BAOBAO","Gadget Flow","https://thegadgetflow.com/product/baobao-dual-mode-robot-companion/","https://www.baobaorobot.com","https://www.baobaorobot.com/contact（問い合わせページ）"),
    (553,"子供・教育","bibo AI Robot Art Toy Character-First Design","bibo","Gadget Flow","https://thegadgetflow.com/product/bibo-ai-robot-art-toy/","https://www.biborobot.com","hello@biborobot.com"),
    (554,"子供・教育","Unitree AS2 Quadruped Robot","Unitree","Gadget Flow","https://thegadgetflow.com/product/unitree-as2-quadruped-robot/","https://www.unitree.com","contact@unitree.com"),
    (555,"子供・教育","SHAPLABOO Magic Box Shadow Puppet Kit","SHAPLABOO","Gadget Flow","https://thegadgetflow.com/product/shaplaboo-halloween-magic-box-shadow-puppet-kit/","https://www.shaplaboo.com","hello@shaplaboo.com"),
    (556,"子供・教育","QUBTRIX Intelligent Wooden Omni-Compatible Bricks","QUBTRIX","Gadget Flow","https://thegadgetflow.com/product/qubtrix-intelligent-wooden-omni-compatible-bricks-combine-with-other-bricks-like-lego/","https://www.qubtrix.com","https://www.qubtrix.com/contact（問い合わせページ）"),
    (557,"ファッション・アクセサリー","MOFT Trackable Snap-on Phone Stand & Wallet MagSafe","MOFT","Gadget Flow","https://thegadgetflow.com/product/trackable-snap-on-phone-stand-wallet-magsafe/","https://www.moft.us","support@moft.us"),
    (558,"ファッション・アクセサリー","James Brand The Lowe Minimal Card Holder","The James Brand","Gadget Flow","https://thegadgetflow.com/product/james-brand-the-lowe-card-holder/","https://thejamesbrand.com","https://thejamesbrand.com/pages/contact-us（問い合わせページ）"),
    (559,"ファッション・アクセサリー","Micro Wallet Finder by Dynomighty RFID Alarm","Dynomighty","Gadget Flow","https://thegadgetflow.com/product/micro-wallet-finder-by-dynomighty-offers-rfid-skimming-alarm/","https://www.dynomighty.com","hello@dynomighty.com"),
    (560,"ファッション・アクセサリー","Uniq Design Lyden DS RFID-Blocking Magnetic Wallet","Uniq Design","Gadget Flow","https://thegadgetflow.com/product/uniq-design-lyden-ds-rfid-blocking-magnetic-wallet/","https://www.uniqaccessory.com","https://www.uniqaccessory.com/contact（問い合わせページ）"),
    (561,"ファッション・アクセサリー","FREITAG Sustainable Wallet Collection","FREITAG","Gadget Flow","https://thegadgetflow.com/product/freitag-new-wallet-collection2024/","https://www.freitag.ch","https://www.freitag.ch/en/contact（問い合わせページ）"),
    (562,"ファッション・アクセサリー","KaTTON Slim Wallet Multitool","KaTTON","Gadget Flow","https://thegadgetflow.com/product/katton-slim-wallet-multitool/","https://www.kattonwallet.com","https://www.kattonwallet.com/contact（問い合わせページ）"),
    (563,"ファッション・アクセサリー","EcoBound Ethically Sourced Leather Modular Wallet","EcoBound","Gadget Flow","https://thegadgetflow.com/product/ecobound-modular/","https://www.ecoboundwallet.com","hello@ecoboundwallet.com"),
    (564,"ファッション・アクセサリー","hardgraft Escape Travel Wallet Passport Wallet","hardgraft","Gadget Flow","https://thegadgetflow.com/product/hardgraft-escape-travel-wallet-is-passport-wallet-that-has-handy-outside-pocket/","https://www.hardgraft.com","hello@hardgraft.com"),
    (565,"ファッション・アクセサリー","hardgraft Atypical Wallet Compact Cash Holder","hardgraft","Gadget Flow","https://thegadgetflow.com/product/hardgraft-atypical-wallet-compact-cash-holder-has-2separate-compartments-for-organization/","https://www.hardgraft.com","hello@hardgraft.com"),
    (566,"ファッション・アクセサリー","Infinity Smart Handbag Instant Color Change","Infinity","Gadget Flow","https://thegadgetflow.com/product/infinity-handbag-smart-luxury/","https://www.infinitybag.com","https://www.infinitybag.com/contact（問い合わせページ）"),
    (567,"ファッション・アクセサリー","AERIONN Forma Titanium Carry-On Luggage","AERIONN","Gadget Flow","https://thegadgetflow.com/product/aerionn-forma-titanium-carry-on/","https://www.aerionn.com","https://www.aerionn.com/contact（問い合わせページ）"),
    (568,"ファッション・アクセサリー","Mission Workshop Rhake LS Modular EDC Backpack","Mission Workshop","Gadget Flow","https://thegadgetflow.com/product/mission-workshop-rhake-ls-everyday-backpack/","https://www.missionworkshop.com","https://www.missionworkshop.com/pages/contact（問い合わせページ）"),
    (569,"ファッション・アクセサリー","UNIT 1 TORCH Backpack with Smart Light Support","UNIT 1","Gadget Flow","https://thegadgetflow.com/product/unit-1-torch-backpack-smart-bag/","https://www.unit1gear.com","hello@unit1gear.com"),
    (570,"ファッション・アクセサリー","WANDRD ROGUE V4 Sling","WANDRD","Gadget Flow","https://thegadgetflow.com/product/rogue-v4-sling-by-wandrd/","https://www.wandrd.com","support@wandrd.com"),
    (571,"ファッション・アクセサリー","Scapade AirPack Smart Travel Backpack","Scapade","Gadget Flow","https://thegadgetflow.com/product/scapade-airpack-travel-backpack/","https://www.scapade.com","hello@scapade.com"),
    (572,"ファッション・アクセサリー","Gyroor Rideable Luggage Suitcase","Gyroor","Gadget Flow","https://thegadgetflow.com/product/gyroor-rideable-luggage-suitcase/","https://www.gyroor.com","support@gyroor.com"),
    (573,"ファッション・アクセサリー","Drobe Modular Suitcase Wardrobe","Drobe","Gadget Flow","https://thegadgetflow.com/product/modular-suitcase-wardrobe/","https://www.drobeluggage.com","https://www.drobeluggage.com/contact（問い合わせページ）"),
    (574,"ファッション・アクセサリー","Lundi TILIO II Cognac 36-hr Leather Briefcase","Lundi","Gadget Flow","https://thegadgetflow.com/product/lundi-36-hr-leather-briefcase-tilio-ii-cognac-travel-briefcase/","https://www.lundi.com","https://www.lundi.com/contact（問い合わせページ）"),
    (575,"ファッション・アクセサリー","Dango Products M1 Lite Cardholder Wallet","Dango Products","Gadget Flow","https://thegadgetflow.com/product/dango-products-m1-lite-cardholder-wallet/","https://dangoproducts.com","https://dangoproducts.com/pages/contact（問い合わせページ）"),
    (576,"ファッション・アクセサリー","TCL Crystalclip with Crystals by Swarovski","TCL","TCL公式サイト","https://thegadgetflow.com/product/tcl-crystalclip-with-crystals-by-swarovski/","https://www.tcl.com","https://www.tcl.com/us/en/support/contact（問い合わせページ）"),
    (577,"ファッション・アクセサリー","Airback Flex Ultimate Smart Backpack","Airback","Gadget Flow","https://thegadgetflow.com/product/airback-flex-ultimate-smart-backpack/","https://www.airback.com","https://www.airback.com/contact（問い合わせページ）"),
    (578,"ファッション・アクセサリー","NOMADE 58 All-in-One Daily Travel Hoodie","NOMADE","Gadget Flow","https://thegadgetflow.com/product/nomade-58-all-in-one-daily-travel-hoodie/","https://www.nomade58.com","hello@nomade58.com"),
    (579,"ファッション・アクセサリー","RE:FORM RE:01 Coin Sleeve Minimal Wallet","RE:FORM","Gadget Flow","https://thegadgetflow.com/product/reform-re01-coin-sleeve/","https://www.reformgoods.com","https://www.reformgoods.com/contact（問い合わせページ）"),
    (580,"ファッション・アクセサリー","4MYTU Max Tank Luggage Set","4MYTU","Gadget Flow","https://thegadgetflow.com/product/4mytu-max-tank-luggage-set/","https://www.4mytu.com","https://www.4mytu.com/contact（問い合わせページ）"),
    (581,"ファッション・アクセサリー","Infi-Pro Anti-Stab Kevlar Backpack","Infi-Pro","Gadget Flow","https://thegadgetflow.com/product/infi-pro-anti-stab-kevlar-backpack/","https://www.infipro.com","https://www.infipro.com/contact（問い合わせページ）"),
    (582,"ファッション・アクセサリー","Arco Headphone Stand Wood Desk Accessory","Arco","Gadget Flow","https://thegadgetflow.com/product/arco-headphone-stand-wood-desk-accessory/","https://www.arcostands.com","https://www.arcostands.com/contact（問い合わせページ）"),
    (583,"クリーニング・収納・整理","Native Union Active Organizer Tech Organizer","Native Union","Gadget Flow","https://thegadgetflow.com/product/active-organizer-tech-organizer/","https://www.nativeunion.com","https://www.nativeunion.com/pages/contact（問い合わせページ）"),
    (584,"クリーニング・収納・整理","Grovemade Matte Desk Pad","Grovemade","Gadget Flow","https://thegadgetflow.com/product/matte-desk-pad/","https://grovemade.com","https://grovemade.com/pages/contact（問い合わせページ）"),
    (585,"クリーニング・収納・整理","Oakywood Desk Shelf Pro Wooden Monitor Stand","Oakywood","Gadget Flow","https://thegadgetflow.com/product/oakywood-desk-shelf-pro-wooden-monitor-stand/","https://oakywood.shop","https://oakywood.shop/pages/contact（問い合わせページ）"),
    (586,"クリーニング・収納・整理","bitplay AquaSeal Waterproof Storage Pouches Dry Bags","bitplay","Gadget Flow","https://thegadgetflow.com/product/bitplay-aquaseal-waterproof-storage-pouch-set-dry-bags/","https://bitplay.com","https://bitplay.com/pages/contact（問い合わせページ）"),
    (587,"クリーニング・収納・整理","Onli Travel Trilogy Modular Travel System","Onli Travel","Gadget Flow","https://thegadgetflow.com/product/onli-travel-trilogy-modular-travel-system/","https://www.onlitravel.com","https://www.onlitravel.com/contact（問い合わせページ）"),
    (588,"クリーニング・収納・整理","Stolp x KonMari Phone Box","Stolp","Gadget Flow","https://thegadgetflow.com/product/stolp-x-konmari-phone-box/","https://www.stolp.shop","hello@stolp.shop"),
    (589,"クリーニング・収納・整理","Holme & Hadfield The Sun Deck Sunglasses Organizer","Holme & Hadfield","Gadget Flow","https://thegadgetflow.com/product/holme-hadfield-the-sun-deck-sunglasses-organizer/","https://www.holmeandhadfield.com","https://www.holmeandhadfield.com/contact（問い合わせページ）"),
    (590,"クリーニング・収納・整理","BlumSafe Display Door Wall Safe for Luxury Watches","BlumSafe","Gadget Flow","https://thegadgetflow.com/product/display-door-high-quality-wall-safe-for-luxury-watches/","https://www.blumsafe.com","https://www.blumsafe.com/contact（問い合わせページ）"),
    (591,"クリーニング・収納・整理","B!POD Food Preservation Vacuum System","B!POD","Gadget Flow","https://thegadgetflow.com/product/bexclamation-markpod-food-preservation-vacuum-systems/","https://www.bpod.com","https://www.bpod.com/contact（問い合わせページ）"),
    (592,"クリーニング・収納・整理","Lucia Gray Stylish Pill Box","Lucia Gray","Gadget Flow","https://thegadgetflow.com/product/stylish-pill-box/","https://www.luciagray.com","https://www.luciagray.com/contact（問い合わせページ）"),
    (593,"クリーニング・収納・整理","elio Collapsible Water Bottle","elio","Gadget Flow","https://thegadgetflow.com/product/elio-collapsible-water-bottle/","https://www.eliobottle.com","hello@eliobottle.com"),
    (594,"クリーニング・収納・整理","Jimmy BX8 Mattress Vacuum Cleaner UV Sanitizing","Jimmy","Gadget Flow","https://thegadgetflow.com/product/jimmy-mattress-vacuum-cleaner-uv-sanitizing/","https://www.jimmy-tech.com","support@jimmy-tech.com"),
    (595,"クリーニング・収納・整理","Tineco FLOOR ONE i7 Fold Wet/Dry Floor Cleaner","Tineco","Gadget Flow","https://thegadgetflow.com/product/tineco-floor-one-i7-fold-wet-dry-floor-cleaner/","https://www.tineco.com","support@tineco.com"),
    (596,"クリーニング・収納・整理","HIZERO H100R Handheld Multi-Surface Cleaner","HIZERO","Gadget Flow","https://thegadgetflow.com/product/hizero-h100r-handheld-multi-surface-cleaner/","https://www.hizero.com","https://www.hizero.com/contact（問い合わせページ）"),
    (597,"クリーニング・収納・整理","HOTO 4-in-1 Autocare Air Duster & Vacuum","HOTO","Gadget Flow","https://thegadgetflow.com/product/hoto-4-in-1-autocare-air-duster-vacuum/","https://www.hototools.com","support@hototools.com"),
    (598,"クリーニング・収納・整理","Dreame C1 Window Cleaning Robot","Dreame Technology","Gadget Flow","https://thegadgetflow.com/product/dreame-c1-window-cleaning-robot/","https://www.dreametech.com","support@dreametech.com"),
    (599,"クリーニング・収納・整理","Beatbot AquaSense X AI Robotic Pool Cleaner","Beatbot","Gadget Flow","https://thegadgetflow.com/product/beatbot-aquasense-x-ai-robotic-pool-cleaner/","https://www.beatbot.com","support@beatbot.com"),
    (600,"クリーニング・収納・整理","xLean TR1 Floor Washing Robot","xLean","Gadget Flow","https://thegadgetflow.com/product/xlean-tr1-floor-washing-robot/","https://www.xlean.com","https://www.xlean.com/contact（問い合わせページ）"),
    (601,"クリーニング・収納・整理","YEEDI M16 Infinity Robot Vacuum","YEEDI","Gadget Flow","https://thegadgetflow.com/product/yeedi-m16-infinity-robot-vacuum/","https://www.yeedi.com","support@yeedi.com"),
    (602,"クリーニング・収納・整理","Honiture P7 Pro Cordless Vacuum Cleaner","Honiture","Gadget Flow","https://thegadgetflow.com/product/honiture-p7-pro-cordless-vacuum-cleaner/","https://www.honiture.com","support@honiture.com"),
    (603,"クリーニング・収納・整理","Chef Preserve Compact Vacuum Sealer","Chef Preserve","Gadget Flow","https://thegadgetflow.com/product/chef-preserve-compact-vacuum-sealer/","https://www.chefpreserve.com","https://www.chefpreserve.com/contact（問い合わせページ）"),
    (604,"クリーニング・収納・整理","Dreame Aqua10 Ultra Roller Robot Vacuum and Mop","Dreame Technology","Gadget Flow","https://thegadgetflow.com/product/dreame-aqua10-ultra-roller-robot-vacuum/","https://www.dreametech.com","support@dreametech.com"),
    (605,"クリーニング・収納・整理","Dreame Cyber X Stair-Climbing Robot Vacuum","Dreame Technology","Gadget Flow","https://thegadgetflow.com/product/dreame-cyber-x-stair-climbing-robot-vacuum/","https://www.dreametech.com","support@dreametech.com"),
    (606,"クリーニング・収納・整理","Roborock Saros Rover Two-Wheel-Leg Robot Vacuum","Roborock","Gadget Flow","https://thegadgetflow.com/product/roborock-saros-rover-robot-vacuum/","https://us.roborock.com","https://us.roborock.com/pages/contact（問い合わせページ）"),
    (607,"クリーニング・収納・整理","Narwal Flow 2 Robot Vacuum","Narwal Robotics","Gadget Flow","https://thegadgetflow.com/product/narwal-flow-2-robovac/","https://us.narwal.com","https://us.narwal.com/pages/contact（問い合わせページ）"),
    (608,"クリーニング・収納・整理","Matic Floor Cleaning Robot","Matic","Gadget Flow","https://thegadgetflow.com/product/matic-floor-cleaning-robot/","https://www.maticrobots.com","hello@maticrobots.com"),
    (609,"スマートホーム・インテリア・照明","Govee Table Lamp Classic","Govee","Govee US","https://thegadgetflow.com/product/govee-table-lamp-classic/","https://us.govee.com","support@govee.com"),
    (610,"スマートホーム・インテリア・照明","Govee Outdoor Spotlights Lite RGBWIC","Govee","Govee US","https://thegadgetflow.com/product/govee-outdoor-spotlights-lite-with-vibrant-rgbwic-colors/","https://us.govee.com","support@govee.com"),
    (611,"スマートホーム・インテリア・照明","Soundcore Nebula X1 Pro 4K AI Mapping Projector Bundle","Anker Soundcore","Gadget Flow","https://thegadgetflow.com/product/anker-soundcore-nebula-x1-pro-plus-spaceflow/","https://www.soundcore.com","support@anker.com"),
    (612,"スマートホーム・インテリア・照明","Bose Lifestyle Ultra Soundbar","Bose","Bose公式サイト","https://thegadgetflow.com/product/bose-lifestyle-ultra-soundbar/","https://www.bose.com","https://www.bose.com/en_us/support/contact_us.html（問い合わせページ）"),
    (613,"スマートホーム・インテリア・照明","Sony BRAVIA Theatre Bar 5 Soundbar","Sony","Sony公式サイト","https://thegadgetflow.com/product/sony-bravia-theatre-bar-5-soundbar/","https://www.sony.com","https://www.sony.com/en_US/support（問い合わせページ）"),
    (614,"スマートホーム・インテリア・照明","Enabot EBO Air 2 Plus Companion Robot","Enabot","Gadget Flow","https://thegadgetflow.com/product/enabot-ebo-air-2-plus-companion-robot/","https://www.enabot.com","support@enabot.com"),
    (615,"スマートホーム・インテリア・照明","Xiaomi Mijia Air Conditioner Eco 2.6kW","Xiaomi","Xiaomi公式サイト","https://thegadgetflow.com/product/xiaomi-mijia-air-conditioner-eco-2-6-kw/","https://www.mi.com","https://www.mi.com/global/support/contact（問い合わせページ）"),
    (616,"スマートホーム・インテリア・照明","Ling! All-in-One Portable AI Learning Companion","Ling","Gadget Flow","https://thegadgetflow.com/product/ling-all-in-one-portable-ai-learning-companion/","https://www.linglearning.ai","https://www.linglearning.ai/contact（問い合わせページ）"),
    (617,"ウェアラブル・ヘルス・フィットネス","JISULIFE Neck Fan Life3 Bladeless Wearable","JISULIFE","Gadget Flow","https://thegadgetflow.com/product/jisulife-neck-fan-life3/","https://www.jisulife.com","support@jisulife.com"),
    (618,"ウェアラブル・ヘルス・フィットネス","Shark ChillPill 3-in-1 Fan Mist and Cooling Plate","Shark","Gadget Flow","https://thegadgetflow.com/product/shark-chillpill-3-in-1-personal-cooling-system/","https://www.sharkclean.com","https://www.sharkclean.com/pages/contact（問い合わせページ）"),
    (619,"ウェアラブル・ヘルス・フィットネス","eufy Wearable Breast Pump S2 Pro","eufy (Anker)","Eufy公式サイト","https://thegadgetflow.com/product/eufy-wearable-breast-pump-s2-pro-breast-pump/","https://www.eufylife.com","support@eufy.com"),
    (620,"ウェアラブル・ヘルス・フィットネス","nfant Thrive Breast Connected Breastfeeding Tracker","nfant","Gadget Flow","https://thegadgetflow.com/product/nfant-thrive-breast-breastfeeding-tracker/","https://www.nfant.com","hello@nfant.com"),
    (621,"ウェアラブル・ヘルス・フィットネス","L'Atitude 52°N BERLIN Smart Glasses","L'Atitude 52°N","Gadget Flow","https://thegadgetflow.com/product/lattitude-52n-berlin-smart-glasses/","https://www.latitude52n.com","https://www.latitude52n.com/contact（問い合わせページ）"),
    (622,"ウェアラブル・ヘルス・フィットネス","Amazfit Helio Armband","Amazfit","Gadget Flow","https://thegadgetflow.com/product/amazfit-helio-armband/","https://www.amazfit.com","support@amazfit.com"),
    (623,"ウェアラブル・ヘルス・フィットネス","Rogbid Fusion 2-in-1 Smart Ring Watch","Rogbid","Gadget Flow","https://thegadgetflow.com/product/rogbid-fusion-2-in-1-smart-ring-watch-smart-wearable/","https://www.rogbid.com","support@rogbid.com"),
    (624,"ウェアラブル・ヘルス・フィットネス","Luna Ring Gen 2 Smart Ring","Luna","Gadget Flow","https://thegadgetflow.com/product/luna-ring-gen-2-smart-ring/","https://www.lunaring.com","https://www.lunaring.com/contact（問い合わせページ）"),
    (625,"ウェアラブル・ヘルス・フィットネス","Omni Health Ring","Omni","Gadget Flow","https://thegadgetflow.com/product/omni-health-ring/","https://www.omnihealth.io","https://www.omnihealth.io/contact（問い合わせページ）"),
    (626,"ウェアラブル・ヘルス・フィットネス","ZEUS Smart Ring Wearable","ZEUS","Gadget Flow","https://thegadgetflow.com/product/zeus-smart-ring-wearable/","https://www.zeusring.com","https://www.zeusring.com/contact（問い合わせページ）"),
    (627,"ウェアラブル・ヘルス・フィットネス","ROLLME G9 Dual-Band GPS Smartwatch","ROLLME","Gadget Flow","https://thegadgetflow.com/product/rollme-g9-dual-band-gps-smartwatch/","https://www.rollme.com","support@rollme.com"),
    (628,"ウェアラブル・ヘルス・フィットネス","Bowflex SelectTech 552 Adjustable Dumbbells","Bowflex","Gadget Flow","https://thegadgetflow.com/product/bowflex-selecttech552-adjustable-dumbbells-switch-weights-between-moves/","https://www.bowflex.com","https://www.bowflex.com/support/contact-us.html（問い合わせページ）"),
    (629,"テクノロジー・ガジェット","ASUS ProArt PA40SU USB4 SSD Enclosure","ASUS","ASUS公式サイト","https://thegadgetflow.com/product/proart-pa40su-ssd-enclosure/","https://www.asus.com","https://www.asus.com/us/support/contact/（問い合わせページ）"),
    (630,"テクノロジー・ガジェット","Agibot A2 Humanoid Robot","AGIBOT","Gadget Flow","https://thegadgetflow.com/product/agibot-a2-humanoid-robot/","https://www.agibot.com","contact@agibot.com"),
    (631,"テクノロジー・ガジェット","LimX Oli Full-Size 31 DoF Humanoid Robot","LimX Dynamics","Gadget Flow","https://thegadgetflow.com/product/limx-oli-humanoid-robot/","https://www.limxdynamics.com","contact@limxdynamics.com"),
    (632,"テクノロジー・ガジェット","Hengbot Sirius Robotic Dog for Kids Education","Hengbot","Gadget Flow","https://thegadgetflow.com/product/hengbot-sirius/","https://www.hengbot.com","contact@hengbot.com"),
    (633,"テクノロジー・ガジェット","Fanttik T8 APEX Case EDC Carry Case","Fanttik","Gadget Flow","https://thegadgetflow.com/product/fanttik-t8-apex-case/","https://www.fanttik.com","support@fanttik.com"),
    (634,"テクノロジー・ガジェット","DuoFlip Flippable MagSafe ID Card Holder","DuoFlip (Sleekstrip)","Gadget Flow","https://thegadgetflow.com/product/sleekstrip-duoflip-flippable-magsafe-id-card-holder/","https://www.sleekstrip.com","https://www.sleekstrip.com/contact（問い合わせページ）"),
    (635,"テクノロジー・ガジェット","Hyundai MobED Autonomous Mobility Robot Platform","Hyundai","Gadget Flow","https://thegadgetflow.com/product/hyundai-mobed-autonomous-robot-platform/","https://www.hyundai.com","https://www.hyundai.com/worldwide/en/company/contact-us（問い合わせページ）"),
    (636,"テクノロジー・ガジェット","Orbitkey Grid Desk Organizer","Orbitkey","Gadget Flow","https://thegadgetflow.com/product/orbitkey-grid-desk-organiser/","https://www.orbitkey.com","https://www.orbitkey.com/pages/contact（問い合わせページ）"),
    (637,"キッチン・調理器具","Saki Luna Electric Kettle Pro","Saki","Saki公式サイト","https://sakiproducts.com/pages/luna-kettle","https://sakiproducts.com","hello@sakiproducts.com"),
    (638,"キッチン・調理器具","Smeg Soda Maker","Smeg","Smeg USA","https://smegstore.us/products/soda-maker-collezione-black-matte-skc01blmus","https://smegstore.us","https://smegstore.us/pages/contact（問い合わせページ）"),
    (639,"キッチン・調理器具","Ninja SLUSHi Max Frozen Drink Maker","Shark Ninja","Ninja公式サイト","https://www.ninjakitchen.com/products/ninja-slushi-max-frozen-drink-maker","https://www.ninjakitchen.com","https://www.ninjakitchen.com/contact-us（問い合わせページ）"),
    (640,"キッチン・調理器具","Ninja Crispi Pro 6-in-1 Air Fryer","Shark Ninja","Ninja公式サイト","https://www.ninjakitchen.com/products/ninja-crispi-pro","https://www.ninjakitchen.com","https://www.ninjakitchen.com/contact-us（問い合わせページ）"),
    (641,"キッチン・調理器具","Our Place Wonder Oven Pro Air Fryer","Our Place","Our Place公式サイト","https://fromourplace.com/products/wonder-oven-pro","https://fromourplace.com","hi@fromourplace.com"),
    (642,"キッチン・調理器具","Breville Eye Q 850 Auto 2-Slice Toaster","Breville","Breville US","https://www.breville.com/en-us/product/bta750","https://www.breville.com","https://www.breville.com/en-us/help/contact-us（問い合わせページ）"),
    (643,"キッチン・調理器具","GE Profile Smart 4-Door French Refrigerator","GE Profile","GE Profile公式サイト","https://www.geappliances.com/ge/refrigerators/french-door-refrigerators/","https://www.geappliances.com","https://www.geappliances.com/ge/contact-us（問い合わせページ）"),
    (644,"キッチン・調理器具","Zwilling Enfinigy Smart Kitchen Scale","Zwilling","Zwilling公式サイト","https://www.zwilling.com/us/zwilling-enfinigy-kitchen-scale/","https://www.zwilling.com","https://www.zwilling.com/us/customer-service（問い合わせページ）"),
    (645,"キッチン・調理器具","Anova Precision Oven Pro","Anova Culinary","Anova公式サイト","https://anovaculinary.com/products/anova-precision-oven","https://anovaculinary.com","support@anovaculinary.com"),
    (646,"キッチン・調理器具","Modernist Pantry Methylcellulose F50 Molecular Gastronomy","Modernist Pantry","Modernist Pantry公式サイト","https://www.modernistpantry.com/methylcellulose-f50.html","https://www.modernistpantry.com","info@modernistpantry.com"),
    (647,"スマートホーム・インテリア・照明","Coway Airmega 400S Smart Air Purifier","Coway","Coway公式サイト","https://cowaymega.com/products/airmega-400s","https://cowaymega.com","support@coway.com"),
    (648,"スマートホーム・インテリア・照明","Blueair Blue Pure 311i+ Max Air Purifier","Blueair","Blueair公式サイト","https://www.blueair.com/en-us/air-purifiers/blue-pure-311i-max/","https://www.blueair.com","support@blueair.com"),
    (649,"スマートホーム・インテリア・照明","Lutron Caseta Smart Dimmer Switch","Lutron","Lutron公式サイト","https://www.casetawireless.com/products/","https://www.lutron.com","https://www.lutron.com/en-US/pages/contact-us（問い合わせページ）"),
    (650,"スマートホーム・インテリア・照明","Nanoleaf Lines Squared Smart Lights","Nanoleaf","Nanoleaf公式サイト","https://nanoleaf.me/en-US/products/nanoleaf-lines-squared/","https://nanoleaf.me","support@nanoleaf.me"),
    (651,"スマートホーム・インテリア・照明","Meross Smart Garage Door Opener","Meross","Meross公式サイト","https://www.meross.com/products/smart-garage-door-opener","https://www.meross.com","support@meross.com"),
    (652,"スマートホーム・インテリア・照明","SwitchBot Hub 3 Smart Home Bridge","SwitchBot","SwitchBot US","https://us.switch-bot.com/products/switchbot-hub-3","https://us.switch-bot.com","support@switchbot.com"),
    (653,"スマートホーム・インテリア・照明","August Smart Lock Wi-Fi","August Home","August Home公式サイト","https://august.com/products/august-smart-lock","https://august.com","support@august.com"),
    (654,"ウェアラブル・ヘルス・フィットネス","FITURE Core Smart Fitness Mirror","Fiture","Fiture公式サイト","https://www.fiture.com/en-us/products/fiture-core","https://www.fiture.com","support@fiture.com"),
    (655,"ウェアラブル・ヘルス・フィットネス","Polar Vantage V3 Multisport GPS Watch","Polar","Polar公式サイト","https://www.polar.com/en/vantage/v3","https://www.polar.com","https://www.polar.com/en/contact（問い合わせページ）"),
    (656,"ウェアラブル・ヘルス・フィットネス","Suunto Race S GPS Sport Watch","Suunto","Suunto公式サイト","https://www.suunto.com/en-US/Products/Sports-Watches/Suunto-Race-S/","https://www.suunto.com","https://www.suunto.com/en-US/customer-care（問い合わせページ）"),
    (657,"ウェアラブル・ヘルス・フィットネス","Withings ScanWatch 2 Hybrid Smartwatch","Withings","Withings US","https://www.withings.com/us/en/scanwatch-2","https://www.withings.com","support@withings.com"),
    (658,"ウェアラブル・ヘルス・フィットネス","Apollo Neuro Wearable Stress Relief Device","Apollo Neuroscience","Apollo Neuro公式サイト","https://apolloneuro.com/products/apollo-neuro-wearable","https://apolloneuro.com","support@apolloneuro.com"),
    (659,"ウェアラブル・ヘルス・フィットネス","Muse S Meditation Brain-Sensing Headband","Muse (Interaxon)","Muse公式サイト","https://choosemuse.com/products/muse-s-brain-sensing-headband","https://choosemuse.com","hello@choosemuse.com"),
    (660,"ウェアラブル・ヘルス・フィットネス","Embr Wave 2 Temperature Wristband","Embr Labs","Embr Labs公式サイト","https://embrlabs.com/products/embr-wave-2","https://embrlabs.com","hello@embrlabs.com"),
    (661,"ウェアラブル・ヘルス・フィットネス","Hyperice Normatec 3 Leg Recovery System","Hyperice","Hyperice公式サイト","https://hyperice.com/products/normatec-3-leg-recovery-system","https://hyperice.com","support@hyperice.com"),
    (662,"ウェアラブル・ヘルス・フィットネス","Sensate 2 Vagus Nerve Stimulator","Sensate","Sensate公式サイト","https://www.getsensate.com/products/sensate-2","https://www.getsensate.com","hello@getsensate.com"),
    (663,"アウトドア・スポーツ・旅行","Garmin inReach Mini 2 Satellite Communicator","Garmin","Garmin公式サイト","https://www.garmin.com/en-US/p/765374/","https://www.garmin.com","https://support.garmin.com/en-US（問い合わせページ）"),
    (664,"アウトドア・スポーツ・旅行","Tentsile Vista Tree Tent","Tentsile","Tentsile公式サイト","https://www.tentsile.com/products/vista-tree-tent","https://www.tentsile.com","hello@tentsile.com"),
    (665,"アウトドア・スポーツ・旅行","Oru Kayak Beach LT Folding Kayak","Oru Kayak","Oru Kayak公式サイト","https://www.orukayak.com/products/beach-lt","https://www.orukayak.com","hello@orukayak.com"),
    (666,"アウトドア・スポーツ・旅行","Yeti Hopper M30 Soft Cooler 2.0","YETI","YETI公式サイト","https://www.yeti.com/en_US/coolers/soft-coolers/hopper-m30-2.0/","https://www.yeti.com","https://www.yeti.com/en_US/support/contact-us.html（問い合わせページ）"),
    (667,"アウトドア・スポーツ・旅行","Matador NanoDry Towel","Matador","Matador公式サイト","https://matadorup.com/collections/towels","https://matadorup.com","help@matadorup.com"),
    (668,"アウトドア・スポーツ・旅行","BioLite CampStove 2+ Wood-Burning Generator Stove","BioLite","BioLite Energy","https://www.bioliteenergy.com/products/campstove-2-plus","https://www.bioliteenergy.com","https://www.bioliteenergy.com/pages/contact（問い合わせページ）"),
    (669,"アウトドア・スポーツ・旅行","Helinox Chair Zero LT Ultralight Camp Chair","Helinox","Helinox公式サイト","https://helinox.com/products/chair-zero-lt","https://helinox.com","https://helinox.com/pages/contact（問い合わせページ）"),
    (670,"アウトドア・スポーツ・旅行","SPOT X Satellite Messenger with Bluetooth","SPOT","SPOT公式サイト","https://www.findmespot.com/en-US/Products/SPOT-X-with-Bluetooth","https://www.findmespot.com","support@findmespot.com"),
    (671,"子供・教育","KiwiCo Tinker Crate Monthly STEM Kit","KiwiCo","KiwiCo公式サイト","https://www.kiwico.com/tinker/subscribe","https://www.kiwico.com","https://www.kiwico.com/pages/contact（問い合わせページ）"),
    (672,"子供・教育","Toniebox Audio System for Kids","Tonie","Tonies US","https://us.tonies.com/products/toniebox-starter-set","https://us.tonies.com","support@tonies.com"),
    (673,"子供・教育","Thames & Kosmos Structural Engineering STEM Kit","Thames & Kosmos","Thames & Kosmos公式サイト","https://www.thamesandkosmos.com/products/structural-engineering-bridges","https://www.thamesandkosmos.com","info@thamesandkosmos.com"),
    (674,"子供・教育","Connetix Magnetic Tiles Starter Set","Connetix","Connetix公式サイト","https://connetixtiles.com/collections/magnetic-tile-sets","https://connetixtiles.com","hello@connetixtiles.com"),
    (675,"子供・教育","Shifu Orboot Earth Interactive AR Globe","Shifu","PlayShifu公式サイト","https://www.playshifu.com/products/orboot-earth","https://www.playshifu.com","hello@playshifu.com"),
    (676,"ファッション・アクセサリー","Herschel Little America Pro Backpack","Herschel Supply","Herschel公式サイト","https://herschel.com/shop/backpacks/little-america-pro-backpack","https://herschel.com","support@herschel.com"),
    (677,"ファッション・アクセサリー","Away The Bigger Carry-On Suitcase","Away","Away公式サイト","https://www.awaytravel.com/luggage/bigger-carry-on","https://www.awaytravel.com","hello@awaytravel.com"),
    (678,"ファッション・アクセサリー","Mack Weldon SHIELD Active Shorts","Mack Weldon","Mack Weldon公式サイト","https://mackweldon.com/products/shield-active-shorts","https://mackweldon.com","hello@mackweldon.com"),
    (679,"ファッション・アクセサリー","Ministry of Supply Apollo Jogger","Ministry of Supply","Ministry of Supply公式サイト","https://ministryofsupply.com/products/apollo-jogger","https://ministryofsupply.com","hello@ministryofsupply.com"),
    (680,"ファッション・アクセサリー","Western Rise StrongCore Merino Shorts","Western Rise","Western Rise公式サイト","https://westernrise.com/products/strongcore-merino-short","https://westernrise.com","hello@westernrise.com"),
    (681,"ファッション・アクセサリー","Montbell Plasma 1000 Down Jacket","Montbell","Montbell USA","https://www.montbell.us/products/disp.php?cat_id=12&p_id=2301341","https://www.montbell.us","info@montbell.us"),
    (682,"ファッション・アクセサリー","Outlier Slim Dungarees Technical Pants","Outlier","Outlier公式サイト","https://outlier.nyc/collections/pants/products/slim-dungarees","https://outlier.nyc","hello@outlier.nyc"),
    (683,"クリーニング・収納・整理","Yamazaki Tower Dish Storage Rack","Yamazaki Home","Yamazaki Home US","https://www.yamazakihome.com/collections/dish-racks","https://www.yamazakihome.com","https://www.yamazakihome.com/pages/contact（問い合わせページ）"),
    (684,"クリーニング・収納・整理","Joseph Joseph Tota 60L Laundry Basket","Joseph Joseph","Joseph Joseph US","https://www.josephjoseph.com/collections/laundry/products/tota-laundry-basket-60l","https://www.josephjoseph.com","support@josephjoseph.com"),
    (685,"クリーニング・収納・整理","Simplehuman Sensor Pump Plus","Simplehuman","Simplehuman公式サイト","https://www.simplehuman.com/products/sensor-pump-plus","https://www.simplehuman.com","customer.service@simplehuman.com"),
    (686,"クリーニング・収納・整理","OXO Good Grips Over-Cabinet-Door Organizer","OXO","OXO公式サイト","https://www.oxo.com/categories/cleaning-and-organization/cabinet-organizers","https://www.oxo.com","help@oxo.com"),
    (687,"クリーニング・収納・整理","Umbra Trigg Floating Shelf","Umbra","Umbra公式サイト","https://www.umbra.com/products/trigg-shelf","https://www.umbra.com","https://www.umbra.com/pages/contact（問い合わせページ）"),
    (688,"クリーニング・収納・整理","Brabantia SortGo 80L Laundry Bin","Brabantia","Brabantia公式サイト","https://www.brabantia.com/us/laundry-baskets/sortgo/","https://www.brabantia.com","https://www.brabantia.com/us/customer-service（問い合わせページ）"),
    (689,"クリーニング・収納・整理","iDesign Linus Cabinet Organizer Set","iDesign","iDesign公式サイト","https://www.idesignliving.com/collections/linus","https://www.idesignliving.com","https://www.idesignliving.com/pages/contact（問い合わせページ）"),
    (690,"テクノロジー・ガジェット","Boox Note Air 3 E-Ink Tablet","Onyx International","Boox公式サイト","https://shop.boox.com/products/noteair3","https://shop.boox.com","support@onyx-international.com"),
    (691,"テクノロジー・ガジェット","Supernote A6 X2 E-Ink Notebook","Ratta Technology","Supernote公式サイト","https://supernote.com/products/supernote-a6x2","https://supernote.com","support@supernote.com"),
    (692,"テクノロジー・ガジェット","Elgato Stream Deck MK.2 Studio Controller","Elgato","Elgato公式サイト","https://www.elgato.com/us/en/p/stream-deck-mk2-black","https://www.elgato.com","https://www.elgato.com/us/en/s/contact-us（問い合わせページ）"),
    (693,"テクノロジー・ガジェット","Rocketbook Fusion Smart Reusable Notebook","Rocketbook","Rocketbook公式サイト","https://getrocketbook.com/products/rocketbook-fusion","https://getrocketbook.com","hello@getrocketbook.com"),
    (694,"テクノロジー・ガジェット","Shure MV7+ USB Podcast Microphone","Shure","Shure公式サイト","https://www.shure.com/en-US/products/microphones/mv/mv7plus","https://www.shure.com","https://www.shure.com/en-US/support/contact-us（問い合わせページ）"),
    (695,"テクノロジー・ガジェット","FIFINE Ampligame AM8 USB Condenser Microphone","FIFINE","FIFINE公式サイト","https://fifinemicrophone.com/products/fifine-ampligame-am8-usb-condenser-microphone","https://fifinemicrophone.com","support@fifinemicrophone.com"),
    (696,"テクノロジー・ガジェット","xTool P2 55W Desktop CO2 Laser Cutter","xTool","xTool公式サイト","https://www.xtool.com/products/xtool-p2","https://www.xtool.com","support@xtool.com"),
    (697,"テクノロジー・ガジェット","Elegoo Saturn 4 Ultra 8K Resin 3D Printer","Elegoo","Elegoo公式サイト","https://www.elegoo.com/products/elegoo-saturn-4-ultra","https://www.elegoo.com","support@elegoo.com"),
    (698,"テクノロジー・ガジェット","EcoFlow DELTA 3 Plus Portable Power Station","EcoFlow","EcoFlow公式サイト","https://www.ecoflow.com/us/products/delta-3-plus","https://www.ecoflow.com","support@ecoflow.com"),
    (699,"テクノロジー・ガジェット","Jackery SolarSaga 200W Solar Panel","Jackery","Jackery公式サイト","https://www.jackery.com/products/solarsaga-200w-solar-panel","https://www.jackery.com","support@jackery.com"),
    (700,"テクノロジー・ガジェット","Insta360 X5 360° Action Camera","Insta360","Insta360公式サイト","https://www.insta360.com/sal/x5","https://www.insta360.com","support@insta360.com"),
    (701,"テクノロジー・ガジェット","Focusrite Scarlett 2i2 4th Gen USB Audio Interface","Focusrite","Focusrite公式サイト","https://focusrite.com/downloads/scarlett-2i2-studio","https://focusrite.com","support@focusrite.com"),
    (702,"テクノロジー・ガジェット","Prusa MK4S 3D Printer","Prusa Research","Prusa公式サイト","https://www.prusa3d.com/product/original-prusa-mk4s-3d-printer/","https://www.prusa3d.com","info@prusa3d.com"),
    (703,"テクノロジー・ガジェット","Nothing Headphone (a) Wireless Headphone","Nothing","Nothing公式サイト","https://us.nothing.tech/products/headphone-a","https://us.nothing.tech","support@nothing.tech"),
    (704,"テクノロジー・ガジェット","Analogue Pocket Retro Game Handheld System","Analogue","Analogue公式サイト","https://www.analogue.co/pocket","https://www.analogue.co","https://www.analogue.co/support（問い合わせページ）"),
    (705,"テクノロジー・ガジェット","Particle Photon 2 IoT Development Kit","Particle","Particle公式サイト","https://store.particle.io/products/photon-2","https://particle.io","https://support.particle.io（問い合わせページ）"),
]

start_row = ws.max_row + 1

for i, row in enumerate(new_data):
    excel_row = start_row + i
    for col, val in enumerate(row, 1):
        cell = ws.cell(row=excel_row, column=col, value=val)
        cell.font = data_font
        cell.border = border
        cell.alignment = data_align
        if excel_row % 2 == 0:
            cell.fill = alt_fill
    cat = row[1]
    cat_cell = ws.cell(row=excel_row, column=2)
    cat_cell.font = cat_font
    cat_cell.fill = cat_fills.get(cat, PatternFill("solid", start_color="404040"))
    ws.row_dimensions[excel_row].height = 28

ws.auto_filter.ref = f"A1:H{ws.max_row}"

output_path = r"C:\Users\hiro\HP0524\海外便利グッズリスト_日本未上陸705件.xlsx"
wb.save(output_path)
print(f"保存完了: {output_path}")
print(f"総行数: {ws.max_row - 1}件")
