from openpyxl import load_workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

wb = load_workbook(r"C:\Users\hiro\HP0524\海外便利グッズリスト_日本未上陸105件.xlsx")
ws = wb["海外便利グッズリスト"]

cat_font = Font(name="Arial", bold=True, color="FFFFFF", size=10)
cat_fills = {
    "キッチン・調理器具": PatternFill("solid", start_color="2E75B6"),
    "スマートホーム・インテリア・照明": PatternFill("solid", start_color="538135"),
    "ウェアラブル・ヘルス・フィットネス": PatternFill("solid", start_color="7030A0"),
    "アウトドア・スポーツ・旅行": PatternFill("solid", start_color="C55A11"),
    "ペット用品": PatternFill("solid", start_color="843C0C"),
    "テクノロジー・ガジェット": PatternFill("solid", start_color="244185"),
    "美容・スキンケア": PatternFill("solid", start_color="C00000"),
    "子供・教育": PatternFill("solid", start_color="375623"),
    "ファッション・アクセサリー": PatternFill("solid", start_color="7B3F00"),
    "クリーニング・収納・整理": PatternFill("solid", start_color="404040"),
}
data_font = Font(name="Arial", size=10)
data_align = Alignment(vertical="center", wrap_text=True)
alt_fill = PatternFill("solid", start_color="EBF3FB")
thin = Side(style="thin", color="CCCCCC")
border = Border(left=thin, right=thin, top=thin, bottom=thin)

# No., カテゴリ, 商品名, メーカー名, 販売ECサイト名, 商品URL, メーカーHP, 連絡先メール
new_data = [
    (106,"キッチン・調理器具","BALMUDA MoonKettle","BALMUDA","BALMUDA USA","https://us.balmuda.com/products/moonkettle","https://us.balmuda.com","https://us.balmuda.com/pages/contact（問い合わせページ）"),
    (107,"キッチン・調理器具","Saki Luna Electric Kettle Pro","Saki","Saki公式サイト","https://sakiproducts.com/pages/luna-kettle","https://sakiproducts.com","hello@sakiproducts.com"),
    (108,"キッチン・調理器具","Breville Joule Turbo Sous Vide","Breville","Breville US","https://www.breville.com/en-us/product/bsv600","https://www.breville.com","https://www.breville.com/en-us/help/contact-us（問い合わせページ）"),
    (109,"キッチン・調理器具","Smeg Soda Maker","Smeg","Smeg USA","https://smegstore.us/products/soda-maker-collezione-black-matte-skc01blmus","https://smegstore.us","https://smegstore.us/pages/contact（問い合わせページ）"),
    (110,"キッチン・調理器具","SodaStream Mix","SodaStream","SodaStream公式サイト","https://sodastream.com/products/mix","https://sodastream.com","https://sodastream.com/pages/contact（問い合わせページ）"),
    (111,"キッチン・調理器具","Ninja SLUSHi Max Frozen Drink Maker","Shark Ninja","Ninja公式サイト","https://www.ninjakitchen.com/products/ninja-slushi-max-frozen-drink-maker","https://www.ninjakitchen.com","https://www.ninjakitchen.com/contact-us（問い合わせページ）"),
    (112,"キッチン・調理器具","Ninja Crispi Pro 6-in-1 Air Fryer","Shark Ninja","Ninja公式サイト","https://www.ninjakitchen.com/products/ninja-crispi-pro","https://www.ninjakitchen.com","https://www.ninjakitchen.com/contact-us（問い合わせページ）"),
    (113,"キッチン・調理器具","KitchenAid Smart Thermometer","KitchenAid","KitchenAid公式サイト","https://www.kitchenaid.com/countertop-appliances/smart-thermometer.html","https://www.kitchenaid.com","https://www.kitchenaid.com/customer-care（問い合わせページ）"),
    (114,"キッチン・調理器具","Our Place Wonder Oven Pro Air Fryer","Our Place","Our Place公式サイト","https://fromourplace.com/products/wonder-oven-pro","https://fromourplace.com","hi@fromourplace.com"),
    (115,"キッチン・調理器具","Ninja Luxe Café Pro Series","Shark Ninja","Ninja公式サイト","https://www.ninjakitchen.com/products/ninja-luxe-cafe-pro-series","https://www.ninjakitchen.com","https://www.ninjakitchen.com/contact-us（問い合わせページ）"),
    (116,"キッチン・調理器具","Weber 22\" Performer Smart Charcoal Grill","Weber","Weber公式サイト","https://www.weber.com/US/en/grills/charcoal-grills/performer-series/","https://www.weber.com","https://www.weber.com/US/en/contact-us（問い合わせページ）"),
    (117,"キッチン・調理器具","Waterdrop TSU Ultrafiltration System","Waterdrop","Waterdrop公式サイト","https://www.waterdropfilter.com/products/waterdrop-tsu","https://www.waterdropfilter.com","support@waterdropfilter.com"),
    (118,"キッチン・調理器具","Waterdrop WD-A2 Countertop RO System","Waterdrop","Waterdrop公式サイト","https://www.waterdropfilter.com/products/wd-a2","https://www.waterdropfilter.com","support@waterdropfilter.com"),
    (119,"キッチン・調理器具","iSpring RCC7AK 6-Stage Alkaline RO Filter","iSpring","iSpring公式サイト","https://www.123filter.com/ispring-rcc7ak","https://www.123filter.com","support@123filter.com"),
    (120,"キッチン・調理器具","GE Profile Smart 4-Door French Refrigerator","GE Profile","GE Profile公式サイト","https://www.geappliances.com/ge/refrigerators/french-door-refrigerators/","https://www.geappliances.com","https://www.geappliances.com/ge/contact-us（問い合わせページ）"),
    (121,"キッチン・調理器具","Breville Eye Q 850 Auto 2-Slice Toaster","Breville","Breville US","https://www.breville.com/en-us/product/bta750","https://www.breville.com","https://www.breville.com/en-us/help/contact-us（問い合わせページ）"),
    (122,"キッチン・調理器具","KitchenAid Artisan Plus 5-Quart Mixer","KitchenAid","KitchenAid公式サイト","https://www.kitchenaid.com/stand-mixers/ksm195ps.html","https://www.kitchenaid.com","https://www.kitchenaid.com/customer-care（問い合わせページ）"),
    (123,"キッチン・調理器具","Roborock F25 GT Cordless Vacuum Mop","Roborock","Roborock US","https://us.roborock.com/products/roborock-f25-gt","https://us.roborock.com","https://us.roborock.com/pages/contact（問い合わせページ）"),
    (124,"キッチン・調理器具","Marcato Pasta Fresca Electric Machine","Marcato","Amazon.com","https://www.amazon.com/Marcato-Electric-Pasta-Machine/dp/B07JNKC3ZZ","https://www.marcato.it","https://www.marcato.it/contact（問い合わせページ）"),
    (125,"スマートホーム・インテリア・照明","Roborock Saros Z70 Robot Vacuum","Roborock","Roborock US","https://us.roborock.com/products/roborock-saros-z70","https://us.roborock.com","https://us.roborock.com/pages/contact（問い合わせページ）"),
    (126,"スマートホーム・インテリア・照明","Dreame X50 Ultra Robot Vacuum & Mop","Dreame Technology","Dreame USA","https://www.dreametech.com/products/x50-ultra-robot-vacuum","https://www.dreametech.com","support@dreametech.com"),
    (127,"スマートホーム・インテリア・照明","Narwal Freo Z10 Turbo Robot Vacuum","Narwal Robotics","Narwal US","https://us.narwal.com/products/narwal-freo-z10-turbo-robot-vacuum-and-mop","https://us.narwal.com","https://us.narwal.com/pages/contact（問い合わせページ）"),
    (128,"スマートホーム・インテリア・照明","SwitchBot K20+ Pro Multi-Tasking Robot","SwitchBot","SwitchBot US","https://us.switch-bot.com/products/switchbot-multitasking-household-robot-k20-pro","https://us.switch-bot.com","support@switchbot.com"),
    (129,"スマートホーム・インテリア・照明","ECOVACS Winbot W2 Pro Omni Window Cleaner","ECOVACS","ECOVACS US","https://www.ecovacs.com/us/winbot-window-cleaning-robot/winbot-w2-pro-omni","https://www.ecovacs.com","https://www.ecovacs.com/us/customer-service/contact-us（問い合わせページ）"),
    (130,"スマートホーム・インテリア・照明","Lockin V7 Max Smart Lock","Lockin","Lockin公式サイト","https://lockin.com/pages/lockin-true-ai-smart-lock-v7-max","https://lockin.com","https://lockin.com/pages/contact（問い合わせページ）"),
    (131,"スマートホーム・インテリア・照明","Aqara Smart Lock U200","Aqara","Aqara US","https://us.aqara.com/products/smart-lock-u200","https://us.aqara.com","https://us.aqara.com/pages/contact（問い合わせページ）"),
    (132,"スマートホーム・インテリア・照明","Govee Table Lamp 2 Pro x JBL","Govee","Govee US","https://us.govee.com/products/govee-table-lamp-2-pro-x-jbl","https://us.govee.com","support@govee.com"),
    (133,"スマートホーム・インテリア・照明","Govee Star Light Projector Nebula","Govee","Govee US","https://us.govee.com/products/govee-star-light-projector-nebula","https://us.govee.com","support@govee.com"),
    (134,"スマートホーム・インテリア・照明","Govee Uplighter Floor Lamp","Govee","Govee US","https://us.govee.com/products/govee-uplighter-floor-lamp","https://us.govee.com","support@govee.com"),
    (135,"スマートホーム・インテリア・照明","Divoom Pixoo-64 Pixel Display","Divoom","Divoom公式サイト","https://divoom.com/products/pixoo-64","https://divoom.com","support@divoom.com"),
    (136,"スマートホーム・インテリア・照明","XGIMI TITAN Noir Max 4K Projector","XGIMI","XGIMI US","https://us.xgimi.com/pages/titan-noir-max","https://us.xgimi.com","https://us.xgimi.com/pages/contact（問い合わせページ）"),
    (137,"スマートホーム・インテリア・照明","Eight Sleep Pod 5 Smart Bed System","Eight Sleep","Eight Sleep公式サイト","https://www.eightsleep.com/product/pod-cover/","https://www.eightsleep.com","support@eightsleep.com"),
    (138,"スマートホーム・インテリア・照明","CabeVibe CabLady S2 Ergonomic Office Chair","CabeVibe","CabeVibe公式サイト","https://www.cabevibe.com/products/cablady-s2-petite-women-ergonomic-office-chair","https://www.cabevibe.com","support@cabevibe.com"),
    (139,"スマートホーム・インテリア・照明","Mui Board Smart Home Controller","Mui Lab","Gadget Flow","https://thegadgetflow.com/product/mui-board-smart-home-display/","https://muilab.com","https://muilab.com/pages/contact（問い合わせページ）"),
    (140,"テクノロジー・ガジェット","eufyMake E1 3D Texture UV Printer","eufyMake (Anker)","eufyMake US","https://www.eufymake.com/products/e1","https://www.eufymake.com","support@eufymake.com"),
    (141,"テクノロジー・ガジェット","Snapmaker U1 Multi-Color 3D Printer","Snapmaker","Snapmaker US","https://us.snapmaker.com/products/snapmaker-u1-3d-printer","https://snapmaker.com","https://support.snapmaker.com/hc/en-us/requests/new（問い合わせページ）"),
    (142,"テクノロジー・ガジェット","NestWorks C500 Desktop CNC Machine","NestWorks","NestWorks AI","https://nestworks-ai.myshopify.com/products/nestworks-c500-vip-deal-reservation","https://nestworks-ai.myshopify.com","https://nestworks-ai.myshopify.com/pages/contact（問い合わせページ）"),
    (143,"テクノロジー・ガジェット","Plaud NotePin S Wearable AI Note Taker","Plaud AI","Plaud公式サイト","https://www.plaud.ai/products/plaud-notepin-s","https://www.plaud.ai","support@plaud.ai"),
    (144,"テクノロジー・ガジェット","SinggoX Pocket Karaoke Machine","SinggoX","SinggoX公式サイト","https://singgox.com/products/","https://singgox.com","https://singgox.com/pages/contact（問い合わせページ）"),
    (145,"テクノロジー・ガジェット","Dreame Leaptic Cube 8K Action Camera","Dreame Technology","Dreame公式サイト","https://www.dreametech.com/products/leaptic-cube","https://www.dreametech.com","support@dreametech.com"),
    (146,"テクノロジー・ガジェット","Rolling Square AirCard Pro Bluetooth Tracker","Rolling Square","Rolling Square公式サイト","https://rollingsquare.com/products/aircard-pro-android-apple-bluetooth-tracker","https://rollingsquare.com","hello@rollingsquare.com"),
    (147,"テクノロジー・ガジェット","Loop Switch 2 Adjustable Earplugs","Loop Earplugs","Loop US","https://us.loopearplugs.com/products/switch","https://us.loopearplugs.com","https://us.loopearplugs.com/pages/contact（問い合わせページ）"),
    (148,"テクノロジー・ガジェット","Amp Fitness AI Home Gym Machine","Amp Fitness","Amp Fit公式サイト","https://ampfit.com/products/","https://ampfit.com","hello@ampfit.com"),
    (149,"テクノロジー・ガジェット","reMarkable Paper Pro Writing Tablet","reMarkable","reMarkable公式サイト","https://remarkable.com/store/remarkable-paper-pro","https://remarkable.com","https://support.remarkable.com/s/contactsupport（問い合わせページ）"),
    (150,"テクノロジー・ガジェット","Nomad ChargeKey V2 USB-C Cable","Nomad Goods","Nomad公式サイト","https://www.nomadgoods.com/products/chargekey-v2-usb-c","https://www.nomadgoods.com","support@nomadgoods.com"),
    (151,"テクノロジー・ガジェット","Analogue Pocket Retro Game System","Analogue","Analogue公式サイト","https://www.analogue.co/pocket","https://www.analogue.co","https://www.analogue.co/support（問い合わせページ）"),
    (152,"テクノロジー・ガジェット","Twelve South AirFly Pro 2 Bluetooth Transmitter","Twelve South","Twelve South公式サイト","https://www.twelvesouth.com/products/airfly-pro","https://www.twelvesouth.com","support@twelvesouth.com"),
    (153,"テクノロジー・ガジェット","HMD Fusion Modular Smartphone","HMD Global","HMD公式サイト","https://www.hmd.com/en_intl/phones/fusion","https://www.hmd.com","https://www.hmd.com/support（問い合わせページ）"),
    (154,"テクノロジー・ガジェット","Fitbit Air Screenless Fitness Tracker","Google Fitbit","Google Store","https://store.google.com/us/category/fitbit","https://www.fitbit.com","https://www.fitbit.com/global/us/contact-us（問い合わせページ）"),
    (155,"テクノロジー・ガジェット","RØDE Streaming Hub Video Mixer","RØDE","RØDE公式サイト","https://rode.com/en/interfaces-and-mixers/rodecaster-series","https://rode.com","support@rode.com"),
    (156,"テクノロジー・ガジェット","Plaud NoteCard AI Voice Recorder","Plaud AI","Plaud公式サイト","https://www.plaud.ai/products/plaud-note","https://www.plaud.ai","support@plaud.ai"),
    (157,"ウェアラブル・ヘルス・フィットネス","Oura Ring 4 Smart Health Ring","Oura","Oura公式サイト","https://ouraring.com/store/rings/oura-ring-4","https://ouraring.com","https://ouraring.com/contact（問い合わせページ）"),
    (158,"ウェアラブル・ヘルス・フィットネス","RingConn Gen 2 Smart Ring","RingConn","RingConn公式サイト","https://ringconn.com/products/ringconn-gen-2","https://ringconn.com","support@ringconn.com"),
    (159,"ウェアラブル・ヘルス・フィットネス","Ultrahuman Ring PRO","Ultrahuman","Ultrahuman US","https://www.ultrahuman.com/us/ring-pro/","https://www.ultrahuman.com","support@ultrahuman.com"),
    (160,"ウェアラブル・ヘルス・フィットネス","WHOOP 5.0 Health & Fitness Tracker","WHOOP","WHOOP公式サイト","https://shop.whoop.com/us/en/","https://www.whoop.com","https://www.whoop.com/us/en/contact-us（問い合わせページ）"),
    (161,"ウェアラブル・ヘルス・フィットネス","COROS NOMAD GPS Adventure Watch","COROS","COROS公式サイト","https://coros.com/buy/nomad","https://coros.com","support@coros.com"),
    (162,"ウェアラブル・ヘルス・フィットネス","Therabody TheraFace Pro Skincare Device","Therabody","Therabody公式サイト","https://www.therabody.com/products/theraface-pro-white","https://www.therabody.com","support@therabody.com"),
    (163,"ウェアラブル・ヘルス・フィットネス","Aescape One Robotic Massage System","Aescape","Aescape Direct","https://one.aescape.com/products/aescape-one-pre-order","https://www.aescape.com","https://www.aescape.com/contact（問い合わせページ）"),
    (164,"ウェアラブル・ヘルス・フィットネス","Bwarm HeatSync Wi-Fi Heated Mattress Pad","Bwarm","Amazon.com","https://www.amazon.com/bwarm-heatsync-heated-mattress-pad/s?k=bwarm+heatsync","https://bwarm.com","https://bwarm.com/pages/contact（問い合わせページ）"),
    (165,"ウェアラブル・ヘルス・フィットネス","Garmin Fenix 8 GPS Smartwatch","Garmin","Garmin公式サイト","https://www.garmin.com/en-US/p/770750/","https://www.garmin.com","https://support.garmin.com/en-US/?supportType=noSelection（問い合わせページ）"),
    (166,"ウェアラブル・ヘルス・フィットネス","Fitbit Ace LTE Kids Fitness Tracker","Google Fitbit","Google Store","https://store.google.com/us/product/fitbit_ace_lte","https://www.fitbit.com","https://www.fitbit.com/global/us/contact-us（問い合わせページ）"),
    (167,"美容・スキンケア","Ulike Air 10 IPL Hair Removal Device","Ulike","Ulike公式サイト","https://www.ulike.com/products/sapphire-air-10-ipl-hair-removal","https://www.ulike.com","support@ulike.com"),
    (168,"美容・スキンケア","Foreo FAQ 502 Full-Spectrum Red Light Device","Foreo","Foreo公式サイト","https://www.foreo.com/faq-swiss-502","https://www.foreo.com","https://www.foreo.com/pages/contact（問い合わせページ）"),
    (169,"美容・スキンケア","NuFace Trinity+ Microcurrent Facial Device","NuFace","NuFace公式サイト","https://www.mynuface.com/products/trinity-starter-kit-smart-microcurrent-facial-toning-device","https://www.mynuface.com","https://www.mynuface.com/pages/contact（問い合わせページ）"),
    (170,"美容・スキンケア","Laduora Duo 4-in-1 Scalp & Hair Care Device","Laduora","Laduora公式サイト","https://laduora.com/products/laduora-duo-hair-care-device-red-light-therapy-microcurrent-scalp-massage","https://laduora.com","hello@laduora.com"),
    (171,"美容・スキンケア","iNewMe NanoHydra Pro AI Skin Hydrator","iNewMe","iNewMe公式サイト","https://inewme.com/nano-hydra-pro","https://inewme.com","support@inewme.com"),
    (172,"美容・スキンケア","Amorepacific Onface Micro-LED Mask","Amorepacific","Global Amore Mall","https://global.amoremall.com/collections/masks","https://global.amoremall.com","cs@amoremall.com"),
    (173,"美容・スキンケア","Therabody TheraGun Prime Muscle Massager","Therabody","Therabody公式サイト","https://www.therabody.com/products/theragun-prime","https://www.therabody.com","support@therabody.com"),
    (174,"美容・スキンケア","Foreo Luna 4 Facial Cleansing Brush","Foreo","Foreo公式サイト","https://www.foreo.com/luna-4","https://www.foreo.com","https://www.foreo.com/pages/contact（問い合わせページ）"),
    (175,"美容・スキンケア","Medicube Booster Pro Skin Care Device","Medicube","Medicube US","https://www.medicube.us/products/booster-pro","https://www.medicube.us","support@medicube.us"),
    (176,"美容・スキンケア","CurrentBody Skin LED Light Therapy Mask","CurrentBody","CurrentBody US","https://www.currentbody.com/products/currentbody-skin-led-light-therapy-mask","https://www.currentbody.com","hello@currentbody.com"),
    (177,"美容・スキンケア","LYMA Laser Skincare Device","LYMA","LYMA公式サイト","https://lyma.life/en-us/products/lyma-laser","https://lyma.life","support@lyma.life"),
    (178,"美容・スキンケア","Shark Glam Air Styling & Drying System","Shark Beauty","Shark Beauty公式サイト","https://www.sharkbeauty.com/products/glam-air","https://www.sharkbeauty.com","https://www.sharkbeauty.com/pages/contact（問い合わせページ）"),
    (179,"アウトドア・スポーツ・旅行","Thermacell EL55 Rechargeable Mosquito Repeller","Thermacell","Thermacell公式サイト","https://www.thermacell.com/products/el55-rechargeable-mosquito-repeller","https://www.thermacell.com","https://www.thermacell.com/pages/contact-us（問い合わせページ）"),
    (180,"アウトドア・スポーツ・旅行","NEMO Dragonfly OSMO Ultralight Tent","NEMO Equipment","NEMO公式サイト","https://www.nemoequipment.com/products/dragonfly-osmo","https://www.nemoequipment.com","hello@nemoequipment.com"),
    (181,"アウトドア・スポーツ・旅行","Helinox Chair Zero LT Ultralight Camp Chair","Helinox","Helinox公式サイト","https://helinox.com/products/chair-zero-lt","https://helinox.com","https://helinox.com/pages/contact（問い合わせページ）"),
    (182,"アウトドア・スポーツ・旅行","BioLite CampStove 2+ Wood-Burning Stove","BioLite","BioLite Energy","https://www.bioliteenergy.com/products/campstove-2-plus","https://www.bioliteenergy.com","https://www.bioliteenergy.com/pages/contact（問い合わせページ）"),
    (183,"アウトドア・スポーツ・旅行","Peak Design Everyday Backpack 20L","Peak Design","Peak Design公式サイト","https://www.peakdesign.com/products/everyday-backpack","https://www.peakdesign.com","https://www.peakdesign.com/pages/contact（問い合わせページ）"),
    (184,"アウトドア・スポーツ・旅行","COROS VERTIX 2S Adventure Watch","COROS","COROS公式サイト","https://coros.com/buy/vertix2s","https://coros.com","support@coros.com"),
    (185,"アウトドア・スポーツ・旅行","Norda 005 Carbon Racing Trail Shoe","Norda","Norda公式サイト","https://www.norda.ca/collections/running","https://www.norda.ca","hello@norda.ca"),
    (186,"アウトドア・スポーツ・旅行","Big Agnes HyperBead Ultralight Tent","Big Agnes","Big Agnes公式サイト","https://www.bigagnes.com/collections/tents","https://www.bigagnes.com","https://www.bigagnes.com/pages/contact-us（問い合わせページ）"),
    (187,"アウトドア・スポーツ・旅行","Dometic COOL-ICE Passive Cooler","Dometic","Dometic公式サイト","https://www.dometic.com/en-us/us/outdoor/icebox-coolers/","https://www.dometic.com","https://www.dometic.com/en-us/us/customer-service（問い合わせページ）"),
    (188,"アウトドア・スポーツ・旅行","NEMO Helio Pressure Shower","NEMO Equipment","NEMO公式サイト","https://www.nemoequipment.com/products/helio-pressure-shower","https://www.nemoequipment.com","hello@nemoequipment.com"),
    (189,"アウトドア・スポーツ・旅行","Goal Zero Nomad 50 Solar Panel","Goal Zero","Goal Zero公式サイト","https://www.goalzero.com/products/nomad-50-solar-panel","https://www.goalzero.com","https://www.goalzero.com/pages/contact-us（問い合わせページ）"),
    (190,"アウトドア・スポーツ・旅行","Osprey Skarab 30 Hydration Pack","Osprey","Osprey公式サイト","https://www.osprey.com/us/en/product/skarab-30-SKARAB30F23.html","https://www.osprey.com","https://www.osprey.com/us/en/support/contact-us（問い合わせページ）"),
    (191,"ペット用品","Fi Series 3+ GPS Smart Dog Collar","Fi","Fi公式サイト","https://shop.fitracking.com/products/smart-collar-v3","https://fitracking.com","hello@fitracking.com"),
    (192,"ペット用品","Tractive Smart GPS Dog Tracker","Tractive","Tractive公式サイト","https://tractive.com/en/pd/gps-tracker-dog","https://tractive.com","support@tractive.com"),
    (193,"ペット用品","Petlibro Scout Smart AI Pet Camera","Petlibro","Petlibro公式サイト","https://petlibro.com/products/scout-smart-camera","https://petlibro.com","support@petlibro.com"),
    (194,"ペット用品","Litter-Robot 4 Automatic Litter Box","Whisker","Litter-Robot公式サイト","https://www.litter-robot.com/litter-robot-4.html","https://www.whisker.com","https://www.litter-robot.com/pages/contact（問い合わせページ）"),
    (195,"ペット用品","Pawport Smart Pet Door","Pawport","Pawport公式サイト","https://pawport.com/products/smart-pet-door","https://pawport.com","hello@pawport.com"),
    (196,"ペット用品","Aqara Smart Pet Feeder C1","Aqara","Aqara US","https://us.aqara.com/products/smart-pet-feeder-c1","https://us.aqara.com","https://us.aqara.com/pages/contact（問い合わせページ）"),
    (197,"ペット用品","PetLibro Granary Smart Automatic Pet Feeder","Petlibro","Petlibro公式サイト","https://petlibro.com/products/granary-wifi-automatic-pet-feeder","https://petlibro.com","support@petlibro.com"),
    (198,"ペット用品","Petcube Cam 360 AI Pet Camera","Petcube","Petcube公式サイト","https://petcube.com/camera-360.html","https://petcube.com","support@petcube.com"),
    (199,"ペット用品","Dogness Smart Interactive Ball","Dogness","Dogness公式サイト","https://www.dogness.com/collections/interactive-toys","https://www.dogness.com","service@dogness.com"),
    (200,"子供・教育","Miko 3 AI Robot for Kids","Miko","Miko公式サイト","https://miko.ai/products/miko-3","https://miko.ai","support@miko.ai"),
    (201,"子供・教育","Loona AI Robot Companion","KEYi Technology","KEYi Robot US","https://us.keyirobot.com/products/loona-us","https://keyirobot.com","support@keyirobot.com"),
    (202,"子供・教育","Makeblock mBot2 Coding Robot","Makeblock","Makeblock公式サイト","https://www.makeblock.com/products/buy-mbot2","https://www.makeblock.com","hi@makeblock.com"),
    (203,"子供・教育","Yoto Player Screen-Free Audio Player","Yoto","Yoto US","https://us.yotoplay.com/yoto-player","https://us.yotoplay.com","hello@yotoplay.com"),
    (204,"子供・教育","Sphero BOLT Coding Robot","Sphero","Sphero公式サイト","https://sphero.com/products/sphero-bolt","https://sphero.com","hello@sphero.com"),
    (205,"子供・教育","Osmo Genius Starter Kit","Osmo","Osmo公式サイト","https://www.playosmo.com/en/genius-kit/","https://www.playosmo.com","https://www.playosmo.com/en/support（問い合わせページ）"),
    (206,"子供・教育","Piper Computer Kit","Piper","Piper公式サイト","https://www.playpiper.com/products/piper-computer-kit","https://www.playpiper.com","https://www.playpiper.com/pages/contact（問い合わせページ）"),
    (207,"子供・教育","Wonder Workshop Dash Robot","Wonder Workshop","Wonder Workshop公式サイト","https://www.makewonder.com/robots/dash/","https://www.makewonder.com","https://www.makewonder.com/pages/contact（問い合わせページ）"),
    (208,"子供・教育","Cozmo 2.0 Emotional AI Robot","Digital Dream Labs","Digital Dream Labs","https://www.digitaldreamlabs.com/products/cozmo","https://www.digitaldreamlabs.com","support@digitaldreamlabs.com"),
    (209,"子供・教育","3Doodler Start+ 3D Printing Pen for Kids","3Doodler","3Doodler公式サイト","https://the3doodler.com/products/3doodler-start-plus","https://the3doodler.com","hello@the3doodler.com"),
    (210,"子供・教育","Botley 3.0 Screen-Free Coding Robot","Learning Resources","Learning Resources","https://www.learningresources.com/botley-3.0-the-coding-robot","https://www.learningresources.com","https://www.learningresources.com/contact（問い合わせページ）"),
    (211,"ファッション・アクセサリー","Peak Design Tech Pouch Organizer","Peak Design","Peak Design公式サイト","https://www.peakdesign.com/products/tech-pouch","https://www.peakdesign.com","https://www.peakdesign.com/pages/contact（問い合わせページ）"),
    (212,"ファッション・アクセサリー","Bellroy Phone Case with Card Pocket","Bellroy","Bellroy公式サイト","https://bellroy.com/products/phone-case","https://bellroy.com","help@bellroy.com"),
    (213,"ファッション・アクセサリー","Ekster Parliament Slim Card Holder Wallet","Ekster","Ekster公式サイト","https://ekster.com/products/parliament-card-holder","https://ekster.com","support@ekster.com"),
    (214,"ファッション・アクセサリー","Nimble Foldable Phone Stand","Nimble","Nimble公式サイト","https://www.gonimble.com/products/foldable-stand","https://www.gonimble.com","hello@gonimble.com"),
    (215,"ファッション・アクセサリー","Baggu Standard Reusable Tote","Baggu","Baggu公式サイト","https://baggu.com/products/standard-baggu","https://baggu.com","hello@baggu.com"),
    (216,"ファッション・アクセサリー","Cotopaxi Allpa 35L Travel Pack","Cotopaxi","Cotopaxi公式サイト","https://www.cotopaxi.com/products/allpa-35l-travel-pack","https://www.cotopaxi.com","hello@cotopaxi.com"),
    (217,"ファッション・アクセサリー","Chrome Industries Urban Ex 2.0 30L Backpack","Chrome Industries","Chrome Industries公式サイト","https://www.chromeindustries.com/products/urban-ex-2-30l-backpack","https://www.chromeindustries.com","https://www.chromeindustries.com/pages/contact（問い合わせページ）"),
    (218,"ファッション・アクセサリー","Secrid Miniwallet RFID Cardholder","Secrid","Secrid公式サイト","https://secrid.com/en-us/products/miniwallet","https://secrid.com","https://secrid.com/en-us/pages/contact（問い合わせページ）"),
    (219,"ファッション・アクセサリー","Tropicfeel Shell 2.0 Travel Backpack","Tropicfeel","Tropicfeel公式サイト","https://www.tropicfeel.com/products/shell-backpack","https://www.tropicfeel.com","hello@tropicfeel.com"),
    (220,"ファッション・アクセサリー","Moment Sling 10L Camera Bag","Moment","Moment公式サイト","https://www.momentlens.co/collections/bags/products/sling-10l-bag","https://www.momentlens.co","support@momentlens.co"),
    (221,"クリーニング・収納・整理","Dyson PencilVac Cordless Stick Vacuum","Dyson","Dyson US","https://www.dyson.com/vacuum-cleaners/sticks/dyson-pencilvac","https://www.dyson.com","https://www.dyson.com/en-US/page/contact（問い合わせページ）"),
    (222,"クリーニング・収納・整理","Dyson Pencilwash Cordless Wet Cleaner","Dyson","Dyson US","https://www.dyson.com/vacuum-cleaners/dyson-pencilwash","https://www.dyson.com","https://www.dyson.com/en-US/page/contact（問い合わせページ）"),
    (223,"クリーニング・収納・整理","Shark AI Ultra Robot Vacuum Self-Empty","Shark","Shark公式サイト","https://www.sharkclean.com/robot-vacuums/shark-ai-ultra","https://www.sharkclean.com","https://www.sharkclean.com/pages/contact（問い合わせページ）"),
    (224,"クリーニング・収納・整理","DEEBOT X11 OmniCyclone Robot Vacuum","ECOVACS","ECOVACS US","https://www.ecovacs.com/us/deebot-robotic-vacuum-cleaner/deebot-x11-omnicyclone","https://www.ecovacs.com","https://www.ecovacs.com/us/customer-service/contact-us（問い合わせページ）"),
    (225,"クリーニング・収納・整理","eufy E20 3-in-1 Robot Vacuum","Eufy (Anker)","Eufy公式サイト","https://www.eufylife.com/products/eufy-robot-vacuum-e20","https://www.eufylife.com","support@eufylife.com"),
    (226,"クリーニング・収納・整理","iRobot Roomba Combo j9+ Robot Vacuum","iRobot","iRobot公式サイト","https://www.irobot.com/en_US/roomba-combo-j9-robot-vacuum-and-mop/4874472.html","https://www.irobot.com","https://www.irobot.com/en_US/contact-us（問い合わせページ）"),
    (227,"クリーニング・収納・整理","Levoit Superior 600S Smart Air Purifier","Levoit","Levoit公式サイト","https://www.levoit.com/products/superior-600s-true-hepa-air-purifier","https://www.levoit.com","support@levoit.com"),
    (228,"クリーニング・収納・整理","BISSELL Little Green Pro Portable Cleaner","BISSELL","BISSELL公式サイト","https://www.bissell.com/little-green-proheat-portable-deep-cleaner","https://www.bissell.com","https://www.bissell.com/pages/contact（問い合わせページ）"),
    (229,"クリーニング・収納・整理","Steam Shot Omni Steam Cleaner","Hamilton Beach","Amazon.com","https://www.amazon.com/Hamilton-Beach-Steam-Shot/dp/B01LYZMXKL","https://www.hamiltonbeach.com","https://www.hamiltonbeach.com/pages/contact（問い合わせページ）"),
    (230,"クリーニング・収納・整理","Yamazaki Tower Magnetic Kitchen Organizer","Yamazaki Home","Yamazaki Home US","https://www.yamazakihome.com/collections/magnetic-storage","https://www.yamazakihome.com","https://www.yamazakihome.com/pages/contact（問い合わせページ）"),
    (231,"スマートホーム・インテリア・照明","Dreame L50 Ultra Robot Vacuum & Mop","Dreame Technology","Dreame USA","https://www.dreametech.com/products/l50-ultra-robot-vacuum","https://www.dreametech.com","support@dreametech.com"),
    (232,"スマートホーム・インテリア・照明","Govee RGBIC Neon Rope Light","Govee","Govee US","https://us.govee.com/products/govee-neon-rope-light","https://us.govee.com","support@govee.com"),
    (233,"スマートホーム・インテリア・照明","Meross Smart Garage Door Opener","Meross","Meross公式サイト","https://www.meross.com/products/smart-garage-door-opener","https://www.meross.com","support@meross.com"),
    (234,"スマートホーム・インテリア・照明","Wyze Cam OG Telephoto Security Camera","Wyze","Wyze公式サイト","https://www.wyze.com/products/wyze-cam-og","https://www.wyze.com","support@wyze.com"),
    (235,"スマートホーム・インテリア・照明","IKEA DIRIGERA Smart Home Hub","IKEA","IKEA US","https://www.ikea.com/us/en/p/dirigera-hub-for-smart-products-white-smart/","https://www.ikea.com","https://www.ikea.com/us/en/customer-service（問い合わせページ）"),
    (236,"スマートホーム・インテリア・照明","Lutron Caseta Smart Dimmer Switch","Lutron","Lutron公式サイト","https://www.casetawireless.com/products/","https://www.lutron.com","https://www.lutron.com/en-US/pages/contact-us（問い合わせページ）"),
    (237,"スマートホーム・インテリア・照明","Nanoleaf Lines Squared Smart Lights","Nanoleaf","Nanoleaf公式サイト","https://nanoleaf.me/en-US/products/nanoleaf-lines-squared/","https://nanoleaf.me","support@nanoleaf.me"),
    (238,"スマートホーム・インテリア・照明","Philips Hue Gradient Signe Floor Lamp","Signify (Philips)","Philips Hue公式サイト","https://www.philips-hue.com/en-us/p/hue-gradient-signe-floor-lamp/4080248U7","https://www.philips-hue.com","https://www.philips-hue.com/en-us/support/contact（問い合わせページ）"),
    (239,"スマートホーム・インテリア・照明","Elgato Key Light Neo Studio Light","Elgato","Elgato公式サイト","https://www.elgato.com/us/en/p/key-light-neo","https://www.elgato.com","https://www.elgato.com/us/en/s/contact-us（問い合わせページ）"),
    (240,"テクノロジー・ガジェット","Anker SOLIX C1000 Portable Power Station","Anker","Anker公式サイト","https://www.anker.com/products/anker-solix-c1000-portable-power-station","https://www.anker.com","support@anker.com"),
    (241,"テクノロジー・ガジェット","Anker 733 Power Bank 65W","Anker","Anker公式サイト","https://www.anker.com/products/anker-733-power-bank","https://www.anker.com","support@anker.com"),
    (242,"テクノロジー・ガジェット","Anker Nano Power Bank 10000mAh","Anker","Anker公式サイト","https://www.anker.com/products/anker-nano-power-bank-10000mah","https://www.anker.com","support@anker.com"),
    (243,"テクノロジー・ガジェット","Ugreen Nexode 300W GaN Charger","UGREEN","UGREEN公式サイト","https://www.ugreen.com/products/nexode-300w-usb-c-charger","https://www.ugreen.com","support@ugreen.com"),
    (244,"テクノロジー・ガジェット","Baseus Blade Slim Laptop Power Bank","Baseus","Baseus公式サイト","https://www.baseus.com/products/blade-100w-laptop-power-bank","https://www.baseus.com","support@baseus.com"),
    (245,"テクノロジー・ガジェット","Soundpeats Air5 Pro+ Wireless Earbuds","Soundpeats","Soundpeats公式サイト","https://www.soundpeats.com/products/soundpeats-air5-pro-plus","https://www.soundpeats.com","support@soundpeats.com"),
    (246,"テクノロジー・ガジェット","Nothing Headphone (a) Wireless Headphone","Nothing","Nothing公式サイト","https://us.nothing.tech/products/headphone-a","https://us.nothing.tech","support@nothing.tech"),
    (247,"テクノロジー・ガジェット","HappyLight Lumi Plus Light Therapy Lamp","Verilux","Amazon.com","https://www.amazon.com/Verilux-HappyLight-Lumi-Plus/dp/B07WHT2G7T","https://verilux.com","support@verilux.com"),
    (248,"テクノロジー・ガジェット","Revel Guitar Chord Trainer","Revel Guitar","Revel Guitar公式サイト","https://revelguitar.com/products/chord-trainer","https://revelguitar.com","hello@revelguitar.com"),
    (249,"テクノロジー・ガジェット","Focusrite Scarlett 2i2 4th Gen USB Audio Interface","Focusrite","Focusrite公式サイト","https://focusrite.com/downloads/scarlett-2i2-studio","https://focusrite.com","support@focusrite.com"),
    (250,"テクノロジー・ガジェット","Prusa MK4S 3D Printer","Prusa Research","Prusa公式サイト","https://www.prusa3d.com/product/original-prusa-mk4s-3d-printer/","https://www.prusa3d.com","info@prusa3d.com"),
    (251,"スマートホーム・インテリア・照明","Level Lock+ Smart Lock","Level Home","Level Home公式サイト","https://level.co/products/lock-plus","https://level.co","https://level.co/support（問い合わせページ）"),
    (252,"スマートホーム・インテリア・照明","Amazon Echo Pop Smart Speaker","Amazon","Amazon公式サイト","https://www.amazon.com/Introducing-Echo-Pop-Compact-Charcoal/dp/B09WX9XFKH","https://www.amazon.com","https://www.amazon.com/hz/contact-us（問い合わせページ）"),
    (253,"スマートホーム・インテリア・照明","Google Nest Learning Thermostat 4th Gen","Google","Google Store","https://store.google.com/us/product/nest_learning_thermostat_4th_gen","https://store.google.com","https://support.google.com/googlenest（問い合わせページ）"),
    (254,"スマートホーム・インテリア・照明","Eufy Security Video Doorbell S380","Eufy (Anker)","Eufy公式サイト","https://www.eufylife.com/products/eufy-security-video-doorbell-s380","https://www.eufylife.com","support@eufylife.com"),
    (255,"スマートホーム・インテリア・照明","SwitchBot Hub 3 Smart Home Bridge","SwitchBot","SwitchBot US","https://us.switch-bot.com/products/switchbot-hub-3","https://us.switch-bot.com","support@switchbot.com"),
    (256,"ウェアラブル・ヘルス・フィットネス","Samsung Galaxy Ring","Samsung","Samsung US","https://www.samsung.com/us/smartphones/galaxy-ring/","https://www.samsung.com","https://www.samsung.com/us/support（問い合わせページ）"),
    (257,"ウェアラブル・ヘルス・フィットネス","FITURE Core Smart Fitness Mirror","Fiture","Fiture公式サイト","https://www.fiture.com/en-us/products/fiture-core","https://www.fiture.com","support@fiture.com"),
    (258,"ウェアラブル・ヘルス・フィットネス","Polar Vantage V3 Multisport Watch","Polar","Polar公式サイト","https://www.polar.com/en/vantage/v3","https://www.polar.com","https://www.polar.com/en/contact（問い合わせページ）"),
    (259,"ウェアラブル・ヘルス・フィットネス","Suunto Race S GPS Sport Watch","Suunto","Suunto公式サイト","https://www.suunto.com/en-US/Products/Sports-Watches/Suunto-Race-S/","https://www.suunto.com","https://www.suunto.com/en-US/customer-care（問い合わせページ）"),
    (260,"ウェアラブル・ヘルス・フィットネス","Withings ScanWatch 2 Hybrid Smartwatch","Withings","Withings US","https://www.withings.com/us/en/scanwatch-2","https://www.withings.com","support@withings.com"),
    (261,"ウェアラブル・ヘルス・フィットネス","Nurvv Run Smart Insoles","Nurvv","Nurvv公式サイト","https://www.nurvv.com/products/nurvv-run","https://www.nurvv.com","hello@nurvv.com"),
    (262,"ウェアラブル・ヘルス・フィットネス","Halo Rise Sleep & Wake Up Alarm","Amazon","Amazon公式サイト","https://www.amazon.com/Halo-Rise-Sleep-Tracker/dp/B09HLKYRMB","https://www.amazon.com","https://www.amazon.com/hz/contact-us（問い合わせページ）"),
    (263,"美容・スキンケア","Skin Inc Optimizer Voyage Tri-Light++","Skin Inc","Skin Inc公式サイト","https://www.skininc.com/collections/devices/products/optimizer-voyage-tri-light","https://www.skininc.com","hello@skininc.com"),
    (264,"美容・スキンケア","LightStim LED Bed Full Body Light Therapy","LightStim","LightStim公式サイト","https://lightstim.com/collections/led-light-therapy-bed","https://lightstim.com","support@lightstim.com"),
    (265,"美容・スキンケア","ZIIP HALO Microcurrent Device","ZIIP Beauty","ZIIP公式サイト","https://www.ziipbeauty.com/products/halo","https://www.ziipbeauty.com","hello@ziipbeauty.com"),
    (266,"美容・スキンケア","Foreo Bear 2 Microcurrent Facial Device","Foreo","Foreo公式サイト","https://www.foreo.com/bear-2","https://www.foreo.com","https://www.foreo.com/pages/contact（問い合わせページ）"),
    (267,"美容・スキンケア","Dermaclara Silicone Patch Set","Dermaclara","Dermaclara公式サイト","https://dermaclara.com/products/skin-care-starter-kit","https://dermaclara.com","support@dermaclara.com"),
    (268,"美容・スキンケア","Nira Precision Laser Anti-Aging Device","Nira","Nira公式サイト","https://niraskin.com/products/nira-precision-laser","https://niraskin.com","support@niraskin.com"),
    (269,"美容・スキンケア","Jovs Venus Pro 2 IPL Hair Removal","Jovs","Jovs公式サイト","https://us.jovs.com/products/venus-pro-ii","https://us.jovs.com","support@jovs.com"),
    (270,"美容・スキンケア","Trophy Skin RejuvadermMD Microdermabrasion Machine","Trophy Skin","Trophy Skin公式サイト","https://www.trophyskin.com/products/rejuvadermmd","https://www.trophyskin.com","support@trophyskin.com"),
    (271,"アウトドア・スポーツ・旅行","Garmin inReach Mini 2 Satellite Communicator","Garmin","Garmin公式サイト","https://www.garmin.com/en-US/p/765374/","https://www.garmin.com","https://support.garmin.com/en-US（問い合わせページ）"),
    (272,"アウトドア・スポーツ・旅行","Black Diamond Spot 400-R Headlamp","Black Diamond","Black Diamond公式サイト","https://www.blackdiamondequipment.com/products/spot-400-r-headlamp","https://www.blackdiamondequipment.com","https://www.blackdiamondequipment.com/pages/contact（問い合わせページ）"),
    (273,"アウトドア・スポーツ・旅行","Hydro Flask Trail Series 32oz Bottle","Hydro Flask","Hydro Flask公式サイト","https://www.hydroflask.com/trail-series-32-oz-water-bottle","https://www.hydroflask.com","https://www.hydroflask.com/help/contact（問い合わせページ）"),
    (274,"アウトドア・スポーツ・旅行","Sea to Summit Ultralight Dry Bag","Sea to Summit","Sea to Summit公式サイト","https://www.seatosummit.com/products/dry-bags/","https://www.seatosummit.com","https://www.seatosummit.com/us/contact（問い合わせページ）"),
    (275,"アウトドア・スポーツ・旅行","LEKI Micro Vario Carbon Trekking Poles","LEKI","LEKI US公式サイト","https://www.leki.com/us/trekking/poles/micro-vario-carbon/","https://www.leki.com","https://www.leki.com/us/service/contact（問い合わせページ）"),
    (276,"アウトドア・スポーツ・旅行","Outdoor Research ActiveIce Spectrum Sun Gloves","Outdoor Research","Outdoor Research公式サイト","https://www.outdoorresearch.com/products/activeice-spectrum-sun-gloves","https://www.outdoorresearch.com","https://www.outdoorresearch.com/pages/contact（問い合わせページ）"),
    (277,"アウトドア・スポーツ・旅行","Therm-a-Rest NeoAir XLite NXT Sleeping Pad","Therm-a-Rest","Therm-a-Rest公式サイト","https://www.thermarest.com/products/neoair-xlite-nxt","https://www.thermarest.com","https://www.thermarest.com/pages/contact（問い合わせページ）"),
    (278,"アウトドア・スポーツ・旅行","KEEN Terradora II Waterproof Boot","KEEN","KEEN公式サイト","https://www.keenfootwear.com/p/1025188.html","https://www.keenfootwear.com","https://www.keenfootwear.com/pages/contact（問い合わせページ）"),
    (279,"アウトドア・スポーツ・旅行","Oru Kayak Beach LT Folding Kayak","Oru Kayak","Oru Kayak公式サイト","https://www.orukayak.com/products/beach-lt","https://www.orukayak.com","hello@orukayak.com"),
    (280,"アウトドア・スポーツ・旅行","Leatherman Signal Multi-Tool","Leatherman","Leatherman公式サイト","https://www.leatherman.com/signal-439.html","https://www.leatherman.com","https://www.leatherman.com/pages/contact（問い合わせページ）"),
    (281,"子供・教育","Osmo Little Genius Starter Kit for iPad","Osmo","Osmo公式サイト","https://www.playosmo.com/en/little-genius/","https://www.playosmo.com","https://www.playosmo.com/en/support（問い合わせページ）"),
    (282,"子供・教育","KiwiCo Tinker Crate Monthly STEM Kit","KiwiCo","KiwiCo公式サイト","https://www.kiwico.com/tinker/subscribe","https://www.kiwico.com","https://www.kiwico.com/pages/contact（問い合わせページ）"),
    (283,"子供・教育","Toniebox Audio System for Kids","Tonie","Tonies US","https://us.tonies.com/products/toniebox-starter-set","https://us.tonies.com","support@tonies.com"),
    (284,"子供・教育","Thames & Kosmos Structural Engineering STEM Kit","Thames & Kosmos","Thames & Kosmos公式サイト","https://www.thamesandkosmos.com/products/structural-engineering-bridges","https://www.thamesandkosmos.com","info@thamesandkosmos.com"),
    (285,"子供・教育","Anki Cozmo AI Robot","Digital Dream Labs","Digital Dream Labs","https://www.digitaldreamlabs.com/products/cozmo","https://www.digitaldreamlabs.com","support@digitaldreamlabs.com"),
    (286,"子供・教育","LittleBits Smart Home Kit","Sphero","Sphero公式サイト","https://sphero.com/products/littlebits-smart-home-kit","https://sphero.com","hello@sphero.com"),
    (287,"ペット用品","Furbo 360° Pet Camera with Treat Toss","Furbo","Furbo公式サイト","https://www.furbo.com/products/furbo-360-dog-camera","https://www.furbo.com","support@furbo.com"),
    (288,"ペット用品","Catit Pixi Smart Treat Dispenser","Catit","Catit公式サイト","https://www.catit.com/pixi-smart-treat-dispenser/","https://www.catit.com","https://www.catit.com/contact（問い合わせページ）"),
    (289,"ペット用品","Petkit Eversweet Smart Pet Water Fountain","Petkit","Petkit公式サイト","https://www.petkit.com/products/petkit-eversweet-smart-pet-water-fountain","https://www.petkit.com","support@petkit.com"),
    (290,"ペット用品","Wagz Freedom Smart Dog Collar","Wagz","Wagz公式サイト","https://wagz.com/products/wagz-freedom-smart-dog-collar","https://wagz.com","support@wagz.com"),
    (291,"クリーニング・収納・整理","Container Store elfa Modular Shelving","The Container Store","The Container Store","https://www.containerstore.com/s/elfa/1","https://www.containerstore.com","https://www.containerstore.com/pages/contact（問い合わせページ）"),
    (292,"クリーニング・収納・整理","Yamazaki Tower Dish Storage Rack","Yamazaki Home","Yamazaki Home US","https://www.yamazakihome.com/collections/dish-racks","https://www.yamazakihome.com","https://www.yamazakihome.com/pages/contact（問い合わせページ）"),
    (293,"クリーニング・収納・整理","OXO Good Grips Over-Cabinet-Door Organizer","OXO","OXO公式サイト","https://www.oxo.com/categories/cleaning-and-organization/cabinet-organizers","https://www.oxo.com","help@oxo.com"),
    (294,"クリーニング・収納・整理","mDesign Stackable Fabric Closet Organizer","mDesign","mDesign公式サイト","https://www.mdesign.com/collections/closet-storage","https://www.mdesign.com","https://www.mdesign.com/pages/contact（問い合わせページ）"),
    (295,"クリーニング・収納・整理","Brabantia SortGo 80L Laundry Bin","Brabantia","Brabantia公式サイト","https://www.brabantia.com/us/laundry-baskets/sortgo/","https://www.brabantia.com","https://www.brabantia.com/us/customer-service（問い合わせページ）"),
    (296,"クリーニング・収納・整理","Joseph Joseph Tota 60L Laundry Basket","Joseph Joseph","Joseph Joseph US","https://www.josephjoseph.com/collections/laundry/products/tota-laundry-basket-60l","https://www.josephjoseph.com","support@josephjoseph.com"),
    (297,"クリーニング・収納・整理","SALT Smart Automatic Soap Dispenser","SALT","Amazon.com","https://www.amazon.com/SALT-Smart-Automatic-Soap-Dispenser/dp/B085B3BJRQ","https://saltsoap.com","https://saltsoap.com/pages/contact（問い合わせページ）"),
    (298,"クリーニング・収納・整理","Simplehuman Sensor Pump Plus","Simplehuman","Simplehuman公式サイト","https://www.simplehuman.com/products/sensor-pump-plus","https://www.simplehuman.com","customer.service@simplehuman.com"),
    (299,"クリーニング・収納・整理","Simplehuman Slim Step Trash Can","Simplehuman","Simplehuman公式サイト","https://www.simplehuman.com/collections/trash-cans","https://www.simplehuman.com","customer.service@simplehuman.com"),
    (300,"クリーニング・収納・整理","iDesign Linus Cabinet Organizer Set","iDesign","iDesign公式サイト","https://www.idesignliving.com/collections/linus","https://www.idesignliving.com","https://www.idesignliving.com/pages/contact（問い合わせページ）"),
    (301,"テクノロジー・ガジェット","Insta360 X5 360° Action Camera","Insta360","Insta360公式サイト","https://www.insta360.com/sal/x5","https://www.insta360.com","support@insta360.com"),
    (302,"テクノロジー・ガジェット","DJI Osmo Pocket 3 Creator Combo","DJI","DJI公式サイト","https://store.dji.com/product/dji-osmo-pocket-3-creator-combo","https://store.dji.com","https://store.dji.com/pages/contact（問い合わせページ）"),
    (303,"テクノロジー・ガジェット","Rode Wireless Pro Microphone System","RØDE","RØDE公式サイト","https://rode.com/en/microphones/wireless/wirelesspro","https://rode.com","support@rode.com"),
    (304,"テクノロジー・ガジェット","Creality K2 Plus Multicolor 3D Printer","Creality","Creality公式サイト","https://www.creality.com/products/creality-k2-plus","https://www.creality.com","support@creality.com"),
    (305,"テクノロジー・ガジェット","xTool P2 55W Desktop CO2 Laser Cutter","xTool","xTool公式サイト","https://www.xtool.com/products/xtool-p2","https://www.xtool.com","support@xtool.com"),
    (306,"テクノロジー・ガジェット","Bambu Lab X1-Carbon 3D Printer","Bambu Lab","Bambu Lab公式サイト","https://store.bambulab.com/products/x1-carbon","https://bambulab.com","support@bambulab.com"),
    (307,"テクノロジー・ガジェット","Elegoo Saturn 4 Ultra 8K Resin Printer","Elegoo","Elegoo公式サイト","https://www.elegoo.com/products/elegoo-saturn-4-ultra","https://www.elegoo.com","support@elegoo.com"),
    (308,"テクノロジー・ガジェット","Jackery Explorer 1000 v2 Power Station","Jackery","Jackery公式サイト","https://www.jackery.com/products/explorer-1000-v2","https://www.jackery.com","support@jackery.com"),
    (309,"テクノロジー・ガジェット","EcoFlow DELTA 3 Plus Power Station","EcoFlow","EcoFlow公式サイト","https://www.ecoflow.com/us/products/delta-3-plus","https://www.ecoflow.com","support@ecoflow.com"),
    (310,"テクノロジー・ガジェット","Bambu Lab A1 Mini Multi-Color 3D Printer","Bambu Lab","Bambu Lab公式サイト","https://store.bambulab.com/products/a1-mini","https://bambulab.com","support@bambulab.com"),
    (311,"ウェアラブル・ヘルス・フィットネス","Apple Watch Ultra 2","Apple","Apple公式サイト","https://www.apple.com/shop/buy-watch/apple-watch-ultra","https://www.apple.com","https://www.apple.com/contact（問い合わせページ）"),
    (312,"ウェアラブル・ヘルス・フィットネス","Garmin Epix Pro GPS Smartwatch","Garmin","Garmin公式サイト","https://www.garmin.com/en-US/p/884585/","https://www.garmin.com","https://support.garmin.com/en-US（問い合わせページ）"),
    (313,"ウェアラブル・ヘルス・フィットネス","Amazfit Active 2 Smartwatch","Amazfit","Amazfit公式サイト","https://www.amazfit.com/en/active-2","https://www.amazfit.com","support@amazfit.com"),
    (314,"ウェアラブル・ヘルス・フィットネス","NowMi Pro Facial Treatment Device","NowMi","NowMi公式サイト","https://www.nowmi.com/products/nowmi-pro","https://www.nowmi.com","info@nowmi.com"),
    (315,"ウェアラブル・ヘルス・フィットネス","Hyperice Normatec 3 Leg Recovery System","Hyperice","Hyperice公式サイト","https://hyperice.com/products/normatec-3-leg-recovery-system","https://hyperice.com","support@hyperice.com"),
    (316,"ウェアラブル・ヘルス・フィットネス","Hyperice Hypervolt 2 Pro Massage Gun","Hyperice","Hyperice公式サイト","https://hyperice.com/products/hypervolt-2-pro","https://hyperice.com","support@hyperice.com"),
    (317,"ウェアラブル・ヘルス・フィットネス","Apollo Neuro Wearable Stress Relief","Apollo Neuroscience","Apollo Neuro公式サイト","https://apolloneuro.com/products/apollo-neuro-wearable","https://apolloneuro.com","support@apolloneuro.com"),
    (318,"ウェアラブル・ヘルス・フィットネス","Muse S Meditation Headband","Muse (Interaxon)","Muse公式サイト","https://choosemuse.com/products/muse-s-brain-sensing-headband","https://choosemuse.com","hello@choosemuse.com"),
    (319,"ウェアラブル・ヘルス・フィットネス","Embr Wave 2 Temperature Wristband","Embr Labs","Embr Labs公式サイト","https://embrlabs.com/products/embr-wave-2","https://embrlabs.com","hello@embrlabs.com"),
    (320,"アウトドア・スポーツ・旅行","Matador NanoDry Towel","Matador","Matador公式サイト","https://matadorup.com/collections/towels","https://matadorup.com","help@matadorup.com"),
    (321,"アウトドア・スポーツ・旅行","Jackery SolarSaga 200W Solar Panel","Jackery","Jackery公式サイト","https://www.jackery.com/products/solarsaga-200w-solar-panel","https://www.jackery.com","support@jackery.com"),
    (322,"アウトドア・スポーツ・旅行","Sea to Summit Ether Light XT Sleeping Pad","Sea to Summit","Sea to Summit公式サイト","https://www.seatosummit.com/products/ether-light-xt-insulated/","https://www.seatosummit.com","https://www.seatosummit.com/us/contact（問い合わせページ）"),
    (323,"アウトドア・スポーツ・旅行","Rab Mythic Ultra 360 Down Sleeping Bag","Rab","Rab公式サイト","https://rab.equipment/us/mythic-ultra-360","https://rab.equipment","https://rab.equipment/us/contact（問い合わせページ）"),
    (324,"アウトドア・スポーツ・旅行","Tentsile Vista Tree Tent","Tentsile","Tentsile公式サイト","https://www.tentsile.com/products/vista-tree-tent","https://www.tentsile.com","hello@tentsile.com"),
    (325,"アウトドア・スポーツ・旅行","Outdoor Vitals Atlas 0° UL Sleeping Bag","Outdoor Vitals","Outdoor Vitals公式サイト","https://www.outdoorvitals.com/products/atlas-0-degree-sleeping-bag","https://www.outdoorvitals.com","support@outdoorvitals.com"),
    (326,"アウトドア・スポーツ・旅行","VSSL Flask Camping Set","VSSL","VSSL公式サイト","https://vsslgear.com/collections/flask","https://vsslgear.com","support@vsslgear.com"),
    (327,"アウトドア・スポーツ・旅行","Gerber Center-Drive Multi-Tool","Gerber Gear","Gerber公式サイト","https://www.gerbertoolsus.com/products/center-drive-multi-tool","https://www.gerbertoolsus.com","https://www.gerbertoolsus.com/pages/contact（問い合わせページ）"),
    (328,"アウトドア・スポーツ・旅行","SPOT X Satellite Messenger","SPOT","SPOT公式サイト","https://www.findmespot.com/en-US/Products/SPOT-X-with-Bluetooth","https://www.findmespot.com","support@findmespot.com"),
    (329,"子供・教育","Nintendo Labo Variety Kit","Nintendo","Nintendo公式サイト","https://www.nintendo.com/store/products/nintendo-labo-toy-con-01-variety-kit-switch/","https://www.nintendo.com","https://www.nintendo.com/en-US/contact（問い合わせページ）"),
    (330,"子供・教育","Snap Circuits STEM Electronic Kit","Elenco","Elenco公式サイト","https://www.elenco.com/product/snap-circuits-stem/","https://www.elenco.com","info@elenco.com"),
    (331,"子供・教育","GraviTrax Starter Set","Ravensburger","Amazon.com","https://www.amazon.com/Ravensburger-GraviTrax-Starter-Set-Marble/dp/B07558KT5Q","https://www.ravensburger.com","https://www.ravensburger.com/en-US/contact（問い合わせページ）"),
    (332,"子供・教育","Kano PC Coding Computer Kit","Kano","Kano公式サイト","https://kano.me/store/us/products/kano-pc","https://kano.me","hello@kano.me"),
    (333,"子供・教育","Shifu Orboot Earth Interactive Globe","Shifu","PlayShifu公式サイト","https://www.playshifu.com/products/orboot-earth","https://www.playshifu.com","hello@playshifu.com"),
    (334,"ファッション・アクセサリー","Tumi Voyageur Hilden Backpack","Tumi","Tumi公式サイト","https://www.tumi.com/c/voyageur-hilden-backpack","https://www.tumi.com","https://www.tumi.com/s/help-center（問い合わせページ）"),
    (335,"ファッション・アクセサリー","Aer City Pack Pro Urban Backpack","Aer","Aer公式サイト","https://www.aersf.com/products/city-pack-pro","https://www.aersf.com","hello@aersf.com"),
    (336,"ファッション・アクセサリー","Saddleback Leather Classic Briefcase","Saddleback Leather","Saddleback公式サイト","https://saddlebackleather.com/classic-briefcase","https://saddlebackleather.com","https://saddlebackleather.com/pages/contact（問い合わせページ）"),
    (337,"ファッション・アクセサリー","Mifold Comfort Go Car Booster Seat","Mifold","Mifold公式サイト","https://mifold.com/products/mifold-comfort-booster-seat","https://mifold.com","info@mifold.com"),
    (338,"ファッション・アクセサリー","Fossil Gen 6 Wellness Edition Smartwatch","Fossil","Fossil公式サイト","https://www.fossil.com/en-us/smartwatches/gen-6-wellness-edition/","https://www.fossil.com","https://www.fossil.com/en-us/help-center（問い合わせページ）"),
    (339,"ファッション・アクセサリー","Montbell Plasma 1000 Down Jacket","Montbell","Montbell USA","https://www.montbell.us/products/disp.php?cat_id=12&p_id=2301341","https://www.montbell.us","info@montbell.us"),
    (340,"ファッション・アクセサリー","Outlier Slim Dungarees Pants","Outlier","Outlier公式サイト","https://outlier.nyc/collections/pants/products/slim-dungarees","https://outlier.nyc","hello@outlier.nyc"),
    (341,"ファッション・アクセサリー","Ministry of Supply Apollo Jogger","Ministry of Supply","Ministry of Supply公式サイト","https://ministryofsupply.com/products/apollo-jogger","https://ministryofsupply.com","hello@ministryofsupply.com"),
    (342,"ファッション・アクセサリー","Western Rise StrongCore Merino Shorts","Western Rise","Western Rise公式サイト","https://westernrise.com/products/strongcore-merino-short","https://westernrise.com","hello@westernrise.com"),
    (343,"クリーニング・収納・整理","Sunbubble Solar-Powered Clothes Dryer","Sunbubble","Amazon.com","https://www.amazon.com/Sunbubble-Solar-Clothes-Dryer/dp/B08N5WNZHL","https://sunbubble.de","info@sunbubble.de"),
    (344,"クリーニング・収納・整理","Polder Expandable Over-Sink Shelf","Polder","Amazon.com","https://www.amazon.com/Polder-Over-Sink-Expandable-Organizer/dp/B002EPTZOE","https://polderproducts.com","https://polderproducts.com/pages/contact（問い合わせページ）"),
    (345,"クリーニング・収納・整理","Elfa Drawer Frame Gliding Cabinet","The Container Store","The Container Store","https://www.containerstore.com/s/elfa-drawer-frames/1","https://www.containerstore.com","https://www.containerstore.com/pages/contact（問い合わせページ）"),
    (346,"クリーニング・収納・整理","Brabantia ReNew Collection Kitchen Set","Brabantia","Brabantia公式サイト","https://www.brabantia.com/us/kitchen/renew-collection/","https://www.brabantia.com","https://www.brabantia.com/us/customer-service（問い合わせページ）"),
    (347,"クリーニング・収納・整理","Umbra Trigg Floating Shelf","Umbra","Umbra公式サイト","https://www.umbra.com/products/trigg-shelf","https://www.umbra.com","https://www.umbra.com/pages/contact（問い合わせページ）"),
    (348,"クリーニング・収納・整理","OXO Stronghold Suction Shower Caddy","OXO","OXO公式サイト","https://www.oxo.com/products/cleaning-and-organization/shower-and-bath/stronghold-suction-shower-caddy","https://www.oxo.com","help@oxo.com"),
    (349,"クリーニング・収納・整理","Eufy HomeVac H30 Cordless Handheld Vacuum","Eufy (Anker)","Eufy公式サイト","https://www.eufylife.com/products/eufy-homevac-h30","https://www.eufylife.com","support@eufylife.com"),
    (350,"スマートホーム・インテリア・照明","Philips Hue Gradient Lightstrip for PC","Signify (Philips)","Philips Hue公式サイト","https://www.philips-hue.com/en-us/p/hue-gradient-lightstrip-for-pc/","https://www.philips-hue.com","https://www.philips-hue.com/en-us/support/contact（問い合わせページ）"),
    (351,"スマートホーム・インテリア・照明","August Smart Lock Wi-Fi","August Home","August Home公式サイト","https://august.com/products/august-smart-lock","https://august.com","support@august.com"),
    (352,"スマートホーム・インテリア・照明","Ring Video Doorbell 4","Ring (Amazon)","Ring公式サイト","https://ring.com/products/video-doorbell-4","https://ring.com","https://support.ring.com（問い合わせページ）"),
    (353,"スマートホーム・インテリア・照明","Arlo Essential 2nd Gen Indoor Camera","Arlo","Arlo公式サイト","https://www.arlo.com/en-us/cameras/arlo-essential-indoor/","https://www.arlo.com","https://www.arlo.com/en-us/support/contact-us（問い合わせページ）"),
    (354,"スマートホーム・インテリア・照明","WiZ Color & Tunable Smart Bulb","WiZ (Signify)","WiZ公式サイト","https://www.wizconnected.com/en-US/c/products/bulbs/","https://www.wizconnected.com","https://www.wizconnected.com/en-US/contact（問い合わせページ）"),
    (355,"テクノロジー・ガジェット","Shure MV7+ USB Podcast Microphone","Shure","Shure公式サイト","https://www.shure.com/en-US/products/microphones/mv/mv7plus","https://www.shure.com","https://www.shure.com/en-US/support/contact-us（問い合わせページ）"),
    (356,"テクノロジー・ガジェット","FIFINE Ampligame AM8 USB Microphone","FIFINE","FIFINE公式サイト","https://fifinemicrophone.com/products/fifine-ampligame-am8-usb-condenser-microphone","https://fifinemicrophone.com","support@fifinemicrophone.com"),
    (357,"テクノロジー・ガジェット","Elgato Stream Deck MK.2","Elgato","Elgato公式サイト","https://www.elgato.com/us/en/p/stream-deck-mk2-black","https://www.elgato.com","https://www.elgato.com/us/en/s/contact-us（問い合わせページ）"),
    (358,"テクノロジー・ガジェット","Rocketbook Fusion Smart Notebook","Rocketbook","Rocketbook公式サイト","https://getrocketbook.com/products/rocketbook-fusion","https://getrocketbook.com","hello@getrocketbook.com"),
    (359,"テクノロジー・ガジェット","Boox Note Air 3 E-Ink Tablet","Onyx International","Boox公式サイト","https://shop.boox.com/products/noteair3","https://shop.boox.com","support@onyx-international.com"),
    (360,"テクノロジー・ガジェット","Supernote A6 X2 E-Ink Notebook","Ratta Technology","Supernote公式サイト","https://supernote.com/products/supernote-a6x2","https://supernote.com","support@supernote.com"),
    (361,"美容・スキンケア","Nurse Jamie UpLift Vibrating Beauty Roller","Nurse Jamie","Nurse Jamie公式サイト","https://nursejamie.com/products/uplift-massaging-beauty-roller","https://nursejamie.com","hello@nursejamie.com"),
    (362,"美容・スキンケア","BeautyBio GloPRO Microneedling Wand","BeautyBio","BeautyBio公式サイト","https://www.beautybio.com/products/glopro-microneedling-regeneration-tool","https://www.beautybio.com","hello@beautybio.com"),
    (363,"美容・スキンケア","StimSure Body Contouring Device","StimSure","Amazon.com","https://www.amazon.com/StimSure-Body-Contouring/dp/B0BDMVCQRC","https://www.stimsure.com","info@stimsure.com"),
    (364,"美容・スキンケア","Dermovia Lace Your Face Compression Mask","Dermovia","Dermovia公式サイト","https://dermovia.com/products/lace-your-face","https://dermovia.com","hello@dermovia.com"),
    (365,"美容・スキンケア","HigherDOSE Red Light Face Mask","HigherDOSE","HigherDOSE公式サイト","https://higherdose.com/products/red-light-face-mask","https://higherdose.com","hello@higherdose.com"),
    (366,"美容・スキンケア","CurrentBody LED Hair Growth Device","CurrentBody","CurrentBody US","https://www.currentbody.com/products/currentbody-skin-led-hair-growth-device","https://www.currentbody.com","hello@currentbody.com"),
    (367,"美容・スキンケア","Solawave 4-in-1 Radiant Renewal Wand","Solawave","Solawave公式サイト","https://solawave.co/products/radiant-renewal-wand","https://solawave.co","hello@solawave.co"),
    (368,"美容・スキンケア","ORA Microneedle Face Roller System","ORA","ORA公式サイト","https://www.oraskincare.com/collections/microneedle-face-roller","https://www.oraskincare.com","https://www.oraskincare.com/pages/contact（問い合わせページ）"),
    (369,"ウェアラブル・ヘルス・フィットネス","Biostrap EVO Health Wristband","Biostrap","Biostrap公式サイト","https://biostrap.com/product/evo/","https://biostrap.com","support@biostrap.com"),
    (370,"ウェアラブル・ヘルス・フィットネス","WHOOP 5.0 MG Medical-Grade Wearable","WHOOP","WHOOP公式サイト","https://shop.whoop.com/us/en/","https://www.whoop.com","https://www.whoop.com/us/en/contact-us（問い合わせページ）"),
    (371,"ウェアラブル・ヘルス・フィットネス","Sensate Vagus Nerve Stimulator","Sensate","Sensate公式サイト","https://www.getsensate.com/products/sensate-2","https://www.getsensate.com","hello@getsensate.com"),
    (372,"ウェアラブル・ヘルス・フィットネス","Halo Sport 2 Neuropriming Headset","Halo Neuroscience","Amazon.com","https://www.amazon.com/Halo-Sport-Neuropriming-Headset/dp/B07CRJXLHG","https://www.haloneuro.com","support@haloneuro.com"),
    (373,"アウトドア・スポーツ・旅行","Zpacks Duplex Ultralight Tent","Zpacks","Zpacks公式サイト","https://zpacks.com/products/duplex-tent","https://zpacks.com","hello@zpacks.com"),
    (374,"アウトドア・スポーツ・旅行","Eagle Creek Pack-It Packing Cube Set","Eagle Creek","Eagle Creek公式サイト","https://www.eaglecreek.com/collections/pack-it-cubes","https://www.eaglecreek.com","support@eaglecreek.com"),
    (375,"アウトドア・スポーツ・旅行","Yeti Hopper M30 Soft Cooler 2.0","YETI","YETI公式サイト","https://www.yeti.com/en_US/coolers/soft-coolers/hopper-m30-2.0/","https://www.yeti.com","https://www.yeti.com/en_US/support/contact-us.html（問い合わせページ）"),
    (376,"アウトドア・スポーツ・旅行","MSR Pocket Rocket Deluxe Camp Stove","MSR","MSR公式サイト","https://www.msrgear.com/stoves/canister-stoves/pocket-rocket-deluxe-stove/11775.html","https://www.msrgear.com","https://www.msrgear.com/support（問い合わせページ）"),
    (377,"アウトドア・スポーツ・旅行","Deuter Guide 44+ Climbing Backpack","Deuter","Deuter公式サイト","https://www.deuter.com/us-en/shop/rucksacks-bags-1/guide-44-10-4910222-4702","https://www.deuter.com","https://www.deuter.com/us-en/contact（問い合わせページ）"),
    (378,"アウトドア・スポーツ・旅行","Black Diamond Mega Light Shelter","Black Diamond","Black Diamond公式サイト","https://www.blackdiamondequipment.com/collections/shelters","https://www.blackdiamondequipment.com","https://www.blackdiamondequipment.com/pages/contact（問い合わせページ）"),
    (379,"ペット用品","Bissell SpotClean Pet Pro Plus","BISSELL","BISSELL公式サイト","https://www.bissell.com/spotclean-pet-pro-plus","https://www.bissell.com","https://www.bissell.com/pages/contact（問い合わせページ）"),
    (380,"ペット用品","Vets Best Advanced Strength Pet Stain Remover","Vets Best","Amazon.com","https://www.amazon.com/Vets-Best-Advanced-Strength-Stain-Remover/dp/B07NH87LH3","https://www.vetsbest.com","https://www.vetsbest.com/pages/contact（問い合わせページ）"),
    (381,"子供・教育","Pixicade Mobile Game Maker","Pixicade","Pixicade公式サイト","https://pixicade.com/products/pixicade-mega-kit","https://pixicade.com","hello@pixicade.com"),
    (382,"子供・教育","Artie 3000 Coding Robot","Educational Insights","Educational Insights公式サイト","https://www.educationalinsights.com/artie-3000-the-coding-robot/","https://www.educationalinsights.com","https://www.educationalinsights.com/pages/contact（問い合わせページ）"),
    (383,"子供・教育","Kamigami Mantis Robot Kit","Dash Robotics","Amazon.com","https://www.amazon.com/Kamigami-Mantis-Robot-Kit/dp/B07GTSHGRJ","https://www.dashrobotics.com","hello@dashrobotics.com"),
    (384,"子供・教育","Magnetic Tiles by Connetix","Connetix","Connetix公式サイト","https://connetixtiles.com/collections/magnetic-tile-sets","https://connetixtiles.com","hello@connetixtiles.com"),
    (385,"テクノロジー・ガジェット","Garmin Prism 3 Smart Windshield Projector","Garmin","Garmin公式サイト","https://www.garmin.com/en-US/p/prism3","https://www.garmin.com","https://support.garmin.com/en-US（問い合わせページ）"),
    (386,"テクノロジー・ガジェット","Notion Home Monitoring System","Notion","Notion公式サイト","https://getnotion.com/products/","https://getnotion.com","support@getnotion.com"),
    (387,"テクノロジー・ガジェット","Flir One Pro LT Thermal Camera","Teledyne FLIR","FLIR公式サイト","https://www.teledyneflir.com/products/flir-one-pro-lt/","https://www.teledyneflir.com","https://www.teledyneflir.com/support/contact（問い合わせページ）"),
    (388,"テクノロジー・ガジェット","Flic 4 Smart Button Hub","Shortcut Labs","Flic公式サイト","https://flic.io/flic4","https://flic.io","hello@flic.io"),
    (389,"スマートホーム・インテリア・照明","Leviton Decora Smart Wi-Fi Mini Plug","Leviton","Leviton公式サイト","https://www.leviton.com/en/products/smart","https://www.leviton.com","https://www.leviton.com/en/customer-support（問い合わせページ）"),
    (390,"スマートホーム・インテリア・照明","Belkin Wemo Smart Plug with Energy Monitor","Belkin","Belkin公式サイト","https://www.belkin.com/smart-plug-with-energy-monitor/","https://www.belkin.com","https://www.belkin.com/support（問い合わせページ）"),
    (391,"スマートホーム・インテリア・照明","Coway Airmega 400S Smart Air Purifier","Coway","Coway公式サイト","https://cowaymega.com/products/airmega-400s","https://cowaymega.com","support@coway.com"),
    (392,"スマートホーム・インテリア・照明","Blueair Blue Pure 311i+ Max Air Purifier","Blueair","Blueair公式サイト","https://www.blueair.com/en-us/air-purifiers/blue-pure-311i-max/","https://www.blueair.com","support@blueair.com"),
    (393,"ファッション・アクセサリー","Herschel Little America Pro Backpack","Herschel Supply","Herschel公式サイト","https://herschel.com/shop/backpacks/little-america-pro-backpack","https://herschel.com","support@herschel.com"),
    (394,"ファッション・アクセサリー","Away The Bigger Carry-On Suitcase","Away","Away公式サイト","https://www.awaytravel.com/luggage/bigger-carry-on","https://www.awaytravel.com","hello@awaytravel.com"),
    (395,"ファッション・アクセサリー","Mack Weldon SHIELD Active Shorts","Mack Weldon","Mack Weldon公式サイト","https://mackweldon.com/products/shield-active-shorts","https://mackweldon.com","hello@mackweldon.com"),
    (396,"ファッション・アクセサリー","Wool& Merino 100-Day Dress","Wool&","Wool&公式サイト","https://wooland.com/collections/dresses","https://wooland.com","hello@wooland.com"),
    (397,"キッチン・調理器具","Anova Precision Oven Pro","Anova Culinary","Anova公式サイト","https://anovaculinary.com/products/anova-precision-oven","https://anovaculinary.com","support@anovaculinary.com"),
    (398,"キッチン・調理器具","Instant Pot Pro Plus Wi-Fi Smart Cooker","Instant Pot","Instant Pot公式サイト","https://www.instantpot.com/ip-pro-plus/","https://www.instantpot.com","https://www.instantpot.com/contact（問い合わせページ）"),
    (399,"キッチン・調理器具","Zwilling Enfinigy Smart Kitchen Scale","Zwilling","Zwilling公式サイト","https://www.zwilling.com/us/zwilling-enfinigy-kitchen-scale/","https://www.zwilling.com","https://www.zwilling.com/us/customer-service（問い合わせページ）"),
    (400,"キッチン・調理器具","Vitamix A3500 Ascent Series Blender","Vitamix","Vitamix公式サイト","https://www.vitamix.com/us/en_us/shop/a3500","https://www.vitamix.com","https://www.vitamix.com/us/en_us/contact（問い合わせページ）"),
    (401,"キッチン・調理器具","Anova Precision Cooker Pro Sous Vide","Anova Culinary","Anova公式サイト","https://anovaculinary.com/products/anova-precision-cooker-pro","https://anovaculinary.com","support@anovaculinary.com"),
    (402,"キッチン・調理器具","Modernist Pantry Methylcellulose F50 Powder","Modernist Pantry","Modernist Pantry公式サイト","https://www.modernistpantry.com/methylcellulose-f50.html","https://www.modernistpantry.com","info@modernistpantry.com"),
    (403,"キッチン・調理器具","Ember Temperature Control Smart Mug 2","Ember","Ember公式サイト","https://ember.com/products/ember-mug-2","https://ember.com","support@ember.com"),
    (404,"テクノロジー・ガジェット","Particle Photon 2 IoT Development Kit","Particle","Particle公式サイト","https://store.particle.io/products/photon-2","https://particle.io","https://support.particle.io（問い合わせページ）"),
    (405,"テクノロジー・ガジェット","Raspberry Pi 5 Single-Board Computer","Raspberry Pi Foundation","Raspberry Pi公式サイト","https://www.raspberrypi.com/products/raspberry-pi-5/","https://www.raspberrypi.com","https://www.raspberrypi.com/about/company（問い合わせページ）"),
]

start_row = ws.max_row + 1

for i, row in enumerate(new_data):
    excel_row = start_row + i
    for col, val in enumerate(row, 1):
        cell = ws.cell(row=excel_row, column=col, value=val)
        cell.font = data_font
        cell.border = border
        cell.alignment = data_align
        if excel_row % 2 == 0:
            cell.fill = alt_fill
    cat = row[1]
    cat_cell = ws.cell(row=excel_row, column=2)
    cat_cell.font = cat_font
    cat_cell.fill = cat_fills.get(cat, PatternFill("solid", start_color="404040"))
    ws.row_dimensions[excel_row].height = 28

# オートフィルターの範囲を更新
ws.auto_filter.ref = f"A1:H{ws.max_row}"

# ファイル名を更新して保存
output_path = r"C:\Users\hiro\HP0524\海外便利グッズリスト_日本未上陸405件.xlsx"
wb.save(output_path)
print(f"保存完了: {output_path}")
print(f"総行数: {ws.max_row - 1}件")
